// Generated by scripts/generate-chains-package.ts. Do not edit.
// Canonical inputs: networks:index; networks:base-mainnet; networks:ethereum-mainnet; networks:mezo-mainnet; networks:mezo-testnet
// Input digest: sha256:110f7150580119d040170dcc964419cdb57130eb19c999d455528606b9e1b421

import type { GeneratedChainsData } from "./generated-types.ts";

export const GENERATED_CHAINS_INPUT_DIGEST = "sha256:110f7150580119d040170dcc964419cdb57130eb19c999d455528606b9e1b421" as const;
export const GENERATED_NETWORK_IDS = [
  "base-mainnet",
  "ethereum-mainnet",
  "mezo-mainnet",
  "mezo-testnet"
] as const;
export const GENERATED_CHAINS_DATA: GeneratedChainsData = {
  "networks": [
    {
      "id": "base-mainnet",
      "environment": "mainnet",
      "profile": "evm",
      "displayName": "Base Mainnet",
      "evmChainId": "8453",
      "cosmosChainId": null,
      "nativeCurrency": {
        "name": "Ether",
        "symbol": "ETH",
        "decimals": 18,
        "cosmosEvmDenom": null
      },
      "explorer": {
        "name": "BaseScan",
        "url": "https://basescan.org"
      },
      "capabilities": {
        "evm": true,
        "evmJsonRpc": true,
        "cosmosSdk": false,
        "nodeCosmosRpc": false,
        "consensusEngine": null,
        "gasCurrency": "native"
      },
      "status": "verified",
      "supportStatus": "supported",
      "reviewStatus": "accepted",
      "verifiedAt": "2026-08-21T00:00:00Z",
      "reviewAfter": "2026-09-21T00:00:00Z",
      "limitations": [
        "Qualified registry provenance review acceptance covers this chain identity and capability profile only; it does not create provider, bridge-route, protocol, or writer support.",
        "No Base RPC endpoint is selected or supported by this record; the public endpoint documented by Base is explicitly rate-limited.",
        "The EVM profile does not claim every optional JSON-RPC method, archive access, subscription, batching, or provider capability."
      ]
    },
    {
      "id": "ethereum-mainnet",
      "environment": "mainnet",
      "profile": "evm",
      "displayName": "Ethereum Mainnet",
      "evmChainId": "1",
      "cosmosChainId": null,
      "nativeCurrency": {
        "name": "Ether",
        "symbol": "ETH",
        "decimals": 18,
        "cosmosEvmDenom": null
      },
      "explorer": {
        "name": "Etherscan",
        "url": "https://etherscan.io"
      },
      "capabilities": {
        "evm": true,
        "evmJsonRpc": true,
        "cosmosSdk": false,
        "nodeCosmosRpc": false,
        "consensusEngine": null,
        "gasCurrency": "native"
      },
      "status": "verified",
      "supportStatus": "supported",
      "reviewStatus": "accepted",
      "verifiedAt": "2026-08-21T00:00:00Z",
      "reviewAfter": "2026-09-21T00:00:00Z",
      "limitations": [
        "Qualified registry provenance review acceptance covers this chain identity and capability profile only; it does not create provider, bridge-route, protocol, or writer support.",
        "No Ethereum RPC endpoint is selected or supported by this record.",
        "The EVM profile does not claim every optional JSON-RPC method, archive access, subscription, batching, or provider capability."
      ]
    },
    {
      "id": "mezo-mainnet",
      "environment": "mainnet",
      "profile": "cosmos-evm",
      "displayName": "Mezo Mainnet",
      "evmChainId": "31612",
      "cosmosChainId": "mezo_31612-1",
      "nativeCurrency": {
        "name": "Bitcoin",
        "symbol": "BTC",
        "decimals": 18,
        "cosmosEvmDenom": "abtc"
      },
      "explorer": {
        "name": "Mezo Explorer",
        "url": "https://explorer.mezo.org"
      },
      "capabilities": {
        "evm": true,
        "evmJsonRpc": true,
        "cosmosSdk": true,
        "nodeCosmosRpc": true,
        "consensusEngine": "CometBFT",
        "gasCurrency": "native"
      },
      "status": "verified",
      "supportStatus": "supported",
      "reviewStatus": "accepted",
      "verifiedAt": "2026-08-17T22:21:02Z",
      "reviewAfter": "2027-02-18T00:00:00Z",
      "limitations": [
        "EVM compatibility is a published chain capability; this record does not claim support for every optional Ethereum JSON-RPC method or EVM feature.",
        "nodeCosmosRpc describes a mezod node capability. MDK does not currently select or support a public Cosmos RPC endpoint.",
        "RPC provider availability is volatile and is owned by the rpc-endpoints resource rather than this chain identity record."
      ]
    },
    {
      "id": "mezo-testnet",
      "environment": "testnet",
      "profile": "cosmos-evm",
      "displayName": "Mezo Testnet",
      "evmChainId": "31611",
      "cosmosChainId": "mezo_31611-1",
      "nativeCurrency": {
        "name": "Bitcoin",
        "symbol": "BTC",
        "decimals": 18,
        "cosmosEvmDenom": "abtc"
      },
      "explorer": {
        "name": "Mezo Testnet Explorer",
        "url": "https://explorer.test.mezo.org"
      },
      "capabilities": {
        "evm": true,
        "evmJsonRpc": true,
        "cosmosSdk": true,
        "nodeCosmosRpc": true,
        "consensusEngine": "CometBFT",
        "gasCurrency": "native"
      },
      "status": "verified",
      "supportStatus": "supported",
      "reviewStatus": "accepted",
      "verifiedAt": "2026-08-17T22:21:02Z",
      "reviewAfter": "2027-02-18T00:00:00Z",
      "limitations": [
        "Testnet state and deployments may reset or diverge from mainnet; this record establishes chain identity, not deployment continuity.",
        "EVM compatibility is a published chain capability; this record does not claim support for every optional Ethereum JSON-RPC method or EVM feature.",
        "nodeCosmosRpc describes a mezod node capability. MDK does not currently select or support a public Cosmos RPC endpoint."
      ]
    }
  ]
};
