// Generated by scripts/generate-incentives-package.ts. Do not edit.
// sha256:b82034110c6288b8d6bfeb90848f247f2ba29f77c90867bcf1875daa45394624
export const INCENTIVES_MODEL = {
  lockConstants: { weekSeconds: "604800", boostPrecision: "1000000000000000000" },
  boostConstants: {
    precision: "1000000000000000000",
    minimumBoost: "1000000000000000000",
    maximumBoost: "5000000000000000000",
  },
  week: "604800",
  voteStartOffset: "3600",
  voteEndOffset: "3600",
  escrows: [
    {
      role: "vebtc-current",
      contractId: "incentives.ve-btc",
      decimals: 18,
      maxLockSeconds: "2419200",
      maxLockSlot: "0x0000000000000000000000000000000000000000000000000000000000000052",
      underlying: "0x7b7c000000000000000000000000000000000000",
      boostable: true,
    },
    {
      role: "vemezo-current",
      contractId: "incentives.ve-mezo",
      decimals: 18,
      maxLockSeconds: "125798400",
      maxLockSlot: "0x0000000000000000000000000000000000000000000000000000000000000052",
      underlying: "0x7b7c000000000000000000000000000000000001",
      boostable: false,
    },
  ],
  rebaseClaimIterationLimit: "50",
} as const;
