// Generated by scripts/generate-incentives-package.ts. Do not edit.
// sha256:0c18e35f992c1e1c602dd65021002db8e4195309f73ae17a1b3ee57ed10f892b
export const INCENTIVES_MODEL = {
  lockConstants: { weekSeconds: "604800", boostPrecision: "1000000000000000000" },
  boostConstants: {
    precision: "1000000000000000000",
    minimumBoost: "1000000000000000000",
    maximumBoost: "5000000000000000000",
  },
  week: "604800",
  voteStartOffset: "3600",
  voteEndOffset: "3600",
  escrows: [
    {
      role: "vebtc-current",
      contractId: "incentives.ve-btc",
      decimals: 18,
      maxLockSeconds: "2419200",
      maxLockSlot: "0x0000000000000000000000000000000000000000000000000000000000000052",
      underlying: "0x7b7c000000000000000000000000000000000000",
      boostable: true,
    },
    {
      role: "vemezo-current",
      contractId: "incentives.ve-mezo",
      decimals: 18,
      maxLockSeconds: "125798400",
      maxLockSlot: "0x0000000000000000000000000000000000000000000000000000000000000052",
      underlying: "0x7b7c000000000000000000000000000000000001",
      boostable: false,
    },
  ],
} as const;
