import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { format } from "prettier";
import { GENERATED_CONTRACTS_DATA } from "../../packages/contracts/src/data.generated.ts";
import { listNetworks } from "../../packages/chains/src/index.ts";
import {
  isContractId,
  resolveRuntimeIdentity,
  ContractRegistryError,
} from "../../packages/contracts/src/index.ts";
import { PRICE_MODEL } from "../../packages/prices/src/model.generated.ts";
import { incentiveEvidenceInputs } from "../lib/incentive-evidence-generation.ts";
import { loadKnowledgeReference } from "../lib/knowledge-reference.ts";
import { object } from "../lib/json.ts";

// Tooling projects existing canonical generators; the runtime never imports their private files.
const root = resolve(import.meta.dirname, "../..");
if (process.argv.slice(2).some((arg) => arg !== "--check"))
  throw new Error("Use --check or no arguments");
const paths = [
  "packages/chains/src/data.generated.ts",
  "packages/contracts/src/data.generated.ts",
  "packages/contracts/src/operations.generated.ts",
  "packages/contracts/src/protocol-operations.generated.ts",
  "packages/contracts/src/ntt.generated.ts",
  "packages/contracts/src/native.generated.ts",
  "packages/prices/src/model.generated.ts",
  "knowledge/protocols/incentives/records/configuration-observations.json",
  "knowledge/protocols/incentives/records/contracts.json",
  "knowledge/protocols/incentives/evidence/mainnet-topology-2026-08-18.json",
];
const configuration = await loadKnowledgeReference(root, {
  moduleId: "protocols/incentives",
  resourceId: "incentives-configuration-observations",
});
const baseline = await loadKnowledgeReference(
  root,
  object(configuration.value, "configuration").baselineReference,
);
paths.push(baseline.path.slice(root.length + 1));
const inputs = await Promise.all(
  paths.map(async (path) => ({
    path,
    sha256: createHash("sha256")
      .update(await readFile(resolve(root, path)))
      .digest("hex"),
  })),
);
const networks = listNetworks().map((network) => {
  const available: string[] = [],
    unavailable: string[] = [];
  for (const deployment of GENERATED_CONTRACTS_DATA.deployments.filter(
    (d) => d.networkId === network.id && d.effectiveUntilExclusiveBlock === null,
  )) {
    if (!isContractId(deployment.contractId)) throw new Error("Unknown generated contract ID");
    try {
      resolveRuntimeIdentity({
        contractId: deployment.contractId,
        networkId: network.id,
        blockNumber: BigInt(deployment.currentCodeFromBlock),
      });
      available.push(deployment.contractId);
    } catch (error) {
      if (
        !(error instanceof ContractRegistryError) ||
        !["AbiUnavailable", "UnsupportedDeploymentState"].includes(error.code)
      )
        throw error;
      unavailable.push(deployment.contractId);
    }
  }
  return {
    id: network.id,
    displayName: network.displayName,
    chainId: network.evmChainId.toString(),
    runtimeContracts: [...new Set(available)].sort(),
    unavailableRuntimeContracts: [...new Set(unavailable)]
      .filter((id) => !available.includes(id))
      .sort(),
  };
});
const model = {
  revision: "2",
  inputDigest: createHash("sha256").update(JSON.stringify(inputs)).digest("hex"),
  inputs,
  networks,
  skip: PRICE_MODEL.skip,
  incentives: await incentiveEvidenceInputs(root),
};
const output = await format(
  `// Generated by scripts/generate/generate-evidence-package.ts. Do not edit.\nexport const EVIDENCE_INPUTS = ${JSON.stringify(model)} as const;\n`,
  { parser: "typescript", printWidth: 100 },
);
const path = resolve(root, "packages/evidence/src/inputs.generated.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(path, "utf8")) !== output) throw new Error("Evidence inputs drifted");
} else await writeFile(path, output);
