// Generated by scripts/generate-prices-package.ts. Do not edit.
// sha256:57dd4cf404063564a58e88c856acc0b08eb4aa3a643ce44c2c1c4c16502cfc84
export const PRICE_MODEL = {
  sourceClasses: [
    "protocol-oracle-state",
    "pushed-feed-observation",
    "offchain-market-reference",
    "dex-derived-observation",
    "dex-execution-quote",
    "stored-analytics-projection",
  ],
  maxPowerOfTenExponent: 77,
  rounding: ["toward-zero", "floor", "ceiling", "nearest-ties-to-even"],
  skip: {
    sourceId: "source.skip-price-oracle-v1",
    feedId: "feed.skip-btc-usd",
    baseAsset: "BTC",
    quoteAsset: "USD",
    sourceDecimals: 18,
    contractId: "oracle.skip-btc-usd",
  },
} as const;
