// Generated by scripts/generate/generate-prices-package.ts. Do not edit.
// sha256:6ffae78eb44f966214fb6fd7054f9b1353376dfe19d9049a76cf0ca481a03f54
export const PRICE_MODEL = {
  sourceClasses: [
    "protocol-oracle-state",
    "pushed-feed-observation",
    "offchain-market-reference",
    "dex-derived-observation",
    "dex-execution-quote",
    "stored-analytics-projection",
  ],
  maxPowerOfTenExponent: 77,
  rounding: ["toward-zero", "floor", "ceiling", "nearest-ties-to-even"],
  skip: {
    sourceId: "source.skip-price-oracle-v1",
    feedId: "feed.skip-btc-usd",
    baseAsset: "BTC",
    quoteAsset: "USD",
    sourceDecimals: 18,
    contractId: "oracle.skip-btc-usd",
  },
} as const;
