// Generated by scripts/generate-redemption-package.ts. Do not edit.
// sha256:4810fe496fba3ed403d2ce5318f157f82ec92b02bee09e82cc6b494959418d66
export const REDEMPTION_MODEL = { decimalPrecision: "1000000000000000000" } as const;
