// Generated by scripts/generate-contracts-package.ts. Do not edit.
// sha256:0ce3c6818240564a89727a1f127df6c03b57eb85f8cc882f5273a63f4879baf2
export const NTT_CONTRACT_INTERFACES = [
  {
    networkId: "mezo-mainnet",
    contractId: "bridge.musd-ntt-manager",
    operationAbi: [
      {
        type: "function",
        name: "cancelOutboundQueuedTransfer",
        inputs: [{ name: "messageSequence", type: "uint64", internalType: "uint64" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "completeInboundQueuedTransfer",
        inputs: [{ name: "digest", type: "bytes32", internalType: "bytes32" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "completeOutboundQueuedTransfer",
        inputs: [{ name: "messageSequence", type: "uint64", internalType: "uint64" }],
        outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "executeMsg",
        inputs: [
          { name: "sourceChainId", type: "uint16", internalType: "uint16" },
          { name: "sourceNttManagerAddress", type: "bytes32", internalType: "bytes32" },
          {
            name: "message",
            type: "tuple",
            internalType: "struct TransceiverStructs.NttManagerMessage",
            components: [
              { name: "id", type: "bytes32", internalType: "bytes32" },
              { name: "sender", type: "bytes32", internalType: "bytes32" },
              { name: "payload", type: "bytes", internalType: "bytes" },
            ],
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "recipientChain", type: "uint16", internalType: "uint16" },
          { name: "recipient", type: "bytes32", internalType: "bytes32" },
          { name: "refundAddress", type: "bytes32", internalType: "bytes32" },
          { name: "shouldQueue", type: "bool", internalType: "bool" },
          { name: "transceiverInstructions", type: "bytes", internalType: "bytes" },
        ],
        outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
        stateMutability: "payable",
      },
    ],
    runtime: {
      addressCodeSha256: "a0bf534c41a0f5ad4843cad431a61e86f62ab7bac5ec4529b5f8e7f2ce7506bc",
      implementationCodeSha256: "cc09c1636ebe402e7975b83627936a22f086f7a22e6639f87491646a700313c9",
      implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    },
  },
  {
    networkId: "ethereum-mainnet",
    contractId: "bridge.musd-ntt-manager",
    operationAbi: [
      {
        type: "function",
        name: "cancelOutboundQueuedTransfer",
        inputs: [{ name: "messageSequence", type: "uint64", internalType: "uint64" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "completeInboundQueuedTransfer",
        inputs: [{ name: "digest", type: "bytes32", internalType: "bytes32" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "completeOutboundQueuedTransfer",
        inputs: [{ name: "messageSequence", type: "uint64", internalType: "uint64" }],
        outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "executeMsg",
        inputs: [
          { name: "sourceChainId", type: "uint16", internalType: "uint16" },
          { name: "sourceNttManagerAddress", type: "bytes32", internalType: "bytes32" },
          {
            name: "message",
            type: "tuple",
            internalType: "struct TransceiverStructs.NttManagerMessage",
            components: [
              { name: "id", type: "bytes32", internalType: "bytes32" },
              { name: "sender", type: "bytes32", internalType: "bytes32" },
              { name: "payload", type: "bytes", internalType: "bytes" },
            ],
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "recipientChain", type: "uint16", internalType: "uint16" },
          { name: "recipient", type: "bytes32", internalType: "bytes32" },
          { name: "refundAddress", type: "bytes32", internalType: "bytes32" },
          { name: "shouldQueue", type: "bool", internalType: "bool" },
          { name: "transceiverInstructions", type: "bytes", internalType: "bytes" },
        ],
        outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
        stateMutability: "payable",
      },
    ],
    runtime: {
      addressCodeSha256: "a0bf534c41a0f5ad4843cad431a61e86f62ab7bac5ec4529b5f8e7f2ce7506bc",
      implementationCodeSha256: "744b0682ca2827dea5983aae8ec85a0a9aa585a743ffc8b4d08f09ff1f127fa4",
      implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    },
  },
  {
    networkId: "base-mainnet",
    contractId: "bridge.musd-ntt-manager",
    operationAbi: [
      {
        type: "function",
        name: "cancelOutboundQueuedTransfer",
        inputs: [{ name: "messageSequence", type: "uint64", internalType: "uint64" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "completeInboundQueuedTransfer",
        inputs: [{ name: "digest", type: "bytes32", internalType: "bytes32" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "completeOutboundQueuedTransfer",
        inputs: [{ name: "messageSequence", type: "uint64", internalType: "uint64" }],
        outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "executeMsg",
        inputs: [
          { name: "sourceChainId", type: "uint16", internalType: "uint16" },
          { name: "sourceNttManagerAddress", type: "bytes32", internalType: "bytes32" },
          {
            name: "message",
            type: "tuple",
            internalType: "struct TransceiverStructs.NttManagerMessage",
            components: [
              { name: "id", type: "bytes32", internalType: "bytes32" },
              { name: "sender", type: "bytes32", internalType: "bytes32" },
              { name: "payload", type: "bytes", internalType: "bytes" },
            ],
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "recipientChain", type: "uint16", internalType: "uint16" },
          { name: "recipient", type: "bytes32", internalType: "bytes32" },
          { name: "refundAddress", type: "bytes32", internalType: "bytes32" },
          { name: "shouldQueue", type: "bool", internalType: "bool" },
          { name: "transceiverInstructions", type: "bytes", internalType: "bytes" },
        ],
        outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
        stateMutability: "payable",
      },
    ],
    runtime: {
      addressCodeSha256: "a0bf534c41a0f5ad4843cad431a61e86f62ab7bac5ec4529b5f8e7f2ce7506bc",
      implementationCodeSha256: "27b489f5fe9a675e69834d279c28e1097c5f1362efc24bfc55e91440d8a55428",
      implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    },
  },
  {
    networkId: "mezo-mainnet",
    contractId: "bridge.musd-wormhole-transceiver",
    operationAbi: [
      {
        type: "function",
        name: "receiveMessage",
        inputs: [{ name: "encodedMessage", type: "bytes", internalType: "bytes" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
    ],
    runtime: {
      addressCodeSha256: "a0bf534c41a0f5ad4843cad431a61e86f62ab7bac5ec4529b5f8e7f2ce7506bc",
      implementationCodeSha256: "d2f3c36e901f7a657a42a1ec26e2ad0283ba7e54a5e5476753499675b362589a",
      implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    },
  },
  {
    networkId: "ethereum-mainnet",
    contractId: "bridge.musd-wormhole-transceiver",
    operationAbi: [
      {
        type: "function",
        name: "receiveMessage",
        inputs: [{ name: "encodedMessage", type: "bytes", internalType: "bytes" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
    ],
    runtime: {
      addressCodeSha256: "a0bf534c41a0f5ad4843cad431a61e86f62ab7bac5ec4529b5f8e7f2ce7506bc",
      implementationCodeSha256: "c2b8734a985595d9e3db2752216c763086f7ad8738449d324514717573290b03",
      implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    },
  },
  {
    networkId: "base-mainnet",
    contractId: "bridge.musd-wormhole-transceiver",
    operationAbi: [
      {
        type: "function",
        name: "receiveMessage",
        inputs: [{ name: "encodedMessage", type: "bytes", internalType: "bytes" }],
        outputs: [],
        stateMutability: "nonpayable",
      },
    ],
    runtime: {
      addressCodeSha256: "a0bf534c41a0f5ad4843cad431a61e86f62ab7bac5ec4529b5f8e7f2ce7506bc",
      implementationCodeSha256: "e5065425ec9581e35b2553bfd93f903a1f63401bc24847a9529be091f8b4f3f2",
      implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    },
  },
] as const;
