// Generated by scripts/generate-borrowing-package.ts. Do not edit.
// Canonical Contracts ABI/catalog and borrowing-formulas; sha256:063688f1ebbd0c224d76185d7a0aa2a4aa46ebf0c388d9b39c1cec0287add1bf
import type { ContractAbiEntry } from "./registry.ts";
import type { ContractRuntimeIdentity } from "./operations.ts";
export const BORROWER_OPERATION_ABI: readonly ContractAbiEntry[] = [
  {
    inputs: [
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "addColl",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collWithdrawal", type: "uint256" },
      { internalType: "uint256", name: "_debtChange", type: "uint256" },
      { internalType: "bool", name: "_isDebtIncrease", type: "bool" },
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "adjustTrove",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "closeTrove", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { internalType: "uint256", name: "_debtAmount", type: "uint256" },
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "openTrove",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "refinance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "repayMUSD",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "withdrawColl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_upperHint", type: "address" },
      { internalType: "address", name: "_lowerHint", type: "address" },
    ],
    name: "withdrawMUSD",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const BORROWING_RUNTIME_IDENTITIES: Readonly<Record<string, ContractRuntimeIdentity>> = {
  "musd.borrower-operations": {
    addressCodeSha256: "1ba7eecc7665df1d88ebfb9dcba15b2af6f6437b2314682e9647baf64e3b2d6c",
    implementationCodeSha256: "75c55798e2c207c67d1523833f7aad2bcd3da3406be9d83f64323bd210ac863c",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.trove-manager": {
    addressCodeSha256: "7640c9211caaf5d71e5a9d3995fb56d75dabaefa156fa2680db514b16f6b0bc9",
    implementationCodeSha256: "49933293a9be2bce6f5627442b6ffd91c438d04304ca8a3fd01aff73ec24de80",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.token": {
    addressCodeSha256: "893d9275226a5019c7ad52628010228272d2124732d951a0ca376aded02b4107",
    implementationCodeSha256: null,
    implementationSlot: null,
  },
  "musd.active-pool": {
    addressCodeSha256: "9e2aee1e83b7c2593236e9343661633234c96a621f9ed7c1be35bdce51a243bb",
    implementationCodeSha256: "19aae362840eb79ff68b15b749b63f016b1cc93d0de3e3e6d6bd3eeb542b54fa",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.default-pool": {
    addressCodeSha256: "18c3bfcf00fb45e2d977b30c74bb18442180bc9569fc3b1a89bc8e8dfe2a6030",
    implementationCodeSha256: "3fdcb2c91a50639be8c5760398760886e0b953810300567c608eb6742c7700a9",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.interest-rate-manager": {
    addressCodeSha256: "8faa5713e1225f7db280c0ea7d00281bca070d12a42f6a3cf5206e1d5dd86669",
    implementationCodeSha256: "435126b121243316439c94f8c30547b1ffeb5a5c52d3b247ddf9866c3b9114c0",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.governable-variables": {
    addressCodeSha256: "75634aacdd8151f2589189f6fa6691ad4966bd0d14611ba97ac6bba90ce26a03",
    implementationCodeSha256: "f12eef8514d81b06341cb2710fcab2d35e1ee1ac041d8fe9afa398da94546dde",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.hint-helpers": {
    addressCodeSha256: "0a08c2b580c47ef9620a7d4ab9df9d76c72b47bab3704ef8db0ea3a7ec9cbbf8",
    implementationCodeSha256: "796027f2bc2ad6bda2d2a612033da99477ec147f7c6b478bd3d72d74ba399467",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.sorted-troves": {
    addressCodeSha256: "e8b0b4aa25fbf22a4b0d5d4081533b6ce276a42c5c6d940975479bcf73342c80",
    implementationCodeSha256: "f5073ca709bc25cdf750adfed15c9690db5ab89cd0a171cc86acb74bfbb30aac",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.coll-surplus-pool": {
    addressCodeSha256: "4bc0aad0ad1344d2a2eb75c6189e924b204ea2bc27529927ffb7eb38c5dec723",
    implementationCodeSha256: "7b87f256868d75137ec485585a0c9bb086768a8d83c3940bb592fad9049d3754",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.price-feed": {
    addressCodeSha256: "c2cf8602ef14df5ce4a0743af85c345b8d1140abde7b8aaef9742c3eebf912ec",
    implementationCodeSha256: "ef553429f103ca555b252204c2cb03725e8f6f87455c291ade868cba3f733939",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.gas-pool": {
    addressCodeSha256: "e1a58915a5eab5e48bf3147a3ac5df4ae0c60f7b15a9ce5319215c2cd3454bad",
    implementationCodeSha256: "10383e5f2f89f25b6940ae34bf99274c607752e1997ee4edeac9e6e53847ee3a",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
  "musd.pcv": {
    addressCodeSha256: "5f17535f300c915c6e0df6fef03bd8286892a78141015b277f194ce8ce151721",
    implementationCodeSha256: "f1ef7b5a871528037257d6099d665cf950d6eb35faa2bc8679e086fd6813cdba",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
  },
};
