// Generated by scripts/generate-core-transaction-model.ts. Do not edit.
// Input digest: sha256:d40480b1ae1d7aa8045c31f9f4e3ef53bc42d2471ae6d4a55ba61135d3734c82

export const GENERATED_TRANSACTION_STATES = [
  {
    "id": "constructed",
    "terminal": false,
    "actionHashRequired": false,
    "approvalHashRequired": false,
    "successLevel": "none"
  },
  {
    "id": "simulated",
    "terminal": false,
    "actionHashRequired": false,
    "approvalHashRequired": false,
    "successLevel": "none"
  },
  {
    "id": "approval-submitted",
    "terminal": false,
    "actionHashRequired": false,
    "approvalHashRequired": true,
    "successLevel": "none"
  },
  {
    "id": "approval-included",
    "terminal": false,
    "actionHashRequired": false,
    "approvalHashRequired": true,
    "successLevel": "none"
  },
  {
    "id": "approval-confirmed",
    "terminal": false,
    "actionHashRequired": false,
    "approvalHashRequired": true,
    "successLevel": "none"
  },
  {
    "id": "submitted",
    "terminal": false,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "none"
  },
  {
    "id": "timed-out",
    "terminal": false,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "none"
  },
  {
    "id": "included",
    "terminal": false,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "included"
  },
  {
    "id": "confirmed",
    "terminal": false,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "confirmed"
  },
  {
    "id": "reconciled",
    "terminal": true,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "protocol-success"
  },
  {
    "id": "validation-failed",
    "terminal": true,
    "actionHashRequired": false,
    "approvalHashRequired": false,
    "successLevel": "failure"
  },
  {
    "id": "simulation-failed",
    "terminal": true,
    "actionHashRequired": false,
    "approvalHashRequired": false,
    "successLevel": "failure"
  },
  {
    "id": "approval-failed",
    "terminal": true,
    "actionHashRequired": false,
    "approvalHashRequired": false,
    "successLevel": "failure"
  },
  {
    "id": "transaction-failed",
    "terminal": true,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "failure"
  },
  {
    "id": "replaced",
    "terminal": true,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "superseded"
  },
  {
    "id": "cancelled",
    "terminal": true,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "cancelled"
  },
  {
    "id": "reorged",
    "terminal": false,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "none"
  },
  {
    "id": "reconciliation-failed",
    "terminal": true,
    "actionHashRequired": true,
    "approvalHashRequired": false,
    "successLevel": "failure"
  }
] as const;

export const GENERATED_TRANSACTION_TRANSITIONS = [
  {
    "from": "constructed",
    "event": "validation-or-build-invalid",
    "to": "validation-failed"
  },
  {
    "from": "constructed",
    "event": "simulation-succeeded",
    "to": "simulated"
  },
  {
    "from": "constructed",
    "event": "simulation-reverted",
    "to": "simulation-failed"
  },
  {
    "from": "simulated",
    "event": "approval-required-and-submitted",
    "to": "approval-submitted"
  },
  {
    "from": "simulated",
    "event": "action-submitted",
    "to": "submitted"
  },
  {
    "from": "approval-submitted",
    "event": "approval-receipt-succeeded",
    "to": "approval-included"
  },
  {
    "from": "approval-submitted",
    "event": "approval-receipt-failed",
    "to": "approval-failed"
  },
  {
    "from": "approval-included",
    "event": "approval-confirmation-threshold-met",
    "to": "approval-confirmed"
  },
  {
    "from": "approval-included",
    "event": "approval-reorg-detected",
    "to": "approval-failed"
  },
  {
    "from": "approval-confirmed",
    "event": "volatile-inputs-revalidated-and-simulation-succeeded",
    "to": "simulated"
  },
  {
    "from": "approval-confirmed",
    "event": "revalidation-or-resimulation-failed",
    "to": "simulation-failed"
  },
  {
    "from": "submitted",
    "event": "wait-timeout",
    "to": "timed-out"
  },
  {
    "from": "submitted",
    "event": "successful-receipt-observed",
    "to": "included"
  },
  {
    "from": "submitted",
    "event": "failed-receipt-observed",
    "to": "transaction-failed"
  },
  {
    "from": "submitted",
    "event": "replacement-observed",
    "to": "replaced"
  },
  {
    "from": "submitted",
    "event": "cancellation-observed",
    "to": "cancelled"
  },
  {
    "from": "timed-out",
    "event": "successful-receipt-observed",
    "to": "included"
  },
  {
    "from": "timed-out",
    "event": "failed-receipt-observed",
    "to": "transaction-failed"
  },
  {
    "from": "timed-out",
    "event": "replacement-observed",
    "to": "replaced"
  },
  {
    "from": "timed-out",
    "event": "cancellation-observed",
    "to": "cancelled"
  },
  {
    "from": "included",
    "event": "confirmation-threshold-met",
    "to": "confirmed"
  },
  {
    "from": "included",
    "event": "reorg-detected",
    "to": "reorged"
  },
  {
    "from": "confirmed",
    "event": "protocol-reconciliation-succeeded",
    "to": "reconciled"
  },
  {
    "from": "confirmed",
    "event": "protocol-reconciliation-failed",
    "to": "reconciliation-failed"
  },
  {
    "from": "confirmed",
    "event": "reorg-detected",
    "to": "reorged"
  },
  {
    "from": "reorged",
    "event": "tracking-resumed",
    "to": "submitted"
  }
] as const;

export const GENERATED_ERROR_DEFINITIONS = {
  "UnsupportedNetwork": {
    "stage": "validate",
    "retry": "after-configuration-change",
    "requiredContext": [
      "requestedNetworkId"
    ]
  },
  "MissingDeployment": {
    "stage": "resolve-deployment",
    "retry": "after-registry-change",
    "requiredContext": [
      "networkId",
      "contractId",
      "validityCoordinate"
    ]
  },
  "ChainMismatch": {
    "stage": "validate",
    "retry": "after-chain-change",
    "requiredContext": [
      "expectedChainId",
      "transportChainId",
      "signerChainId"
    ]
  },
  "InvalidUnits": {
    "stage": "validate",
    "retry": "after-input-change",
    "requiredContext": [
      "field",
      "input",
      "expectedDecimals"
    ]
  },
  "StaleQuote": {
    "stage": "pre-submit",
    "retry": "after-requote",
    "requiredContext": [
      "quoteBlock",
      "currentBlock",
      "freshnessPolicy"
    ]
  },
  "PartialReadError": {
    "stage": "read",
    "retry": "required-item-policy",
    "requiredContext": [
      "blockCoordinate",
      "failedItems",
      "requiredItems"
    ]
  },
  "ProviderError": {
    "stage": "transport",
    "retry": "operation-dependent",
    "requiredContext": [
      "providerId",
      "operation",
      "acceptedUnknown"
    ]
  },
  "ContractRevert": {
    "stage": "simulation",
    "retry": "after-state-or-input-change",
    "requiredContext": [
      "contractId",
      "entrypoint",
      "decodedError",
      "rawRevertData"
    ]
  },
  "ApprovalError": {
    "stage": "approval",
    "retry": "after-allowance-or-policy-check",
    "requiredContext": [
      "tokenContractId",
      "spender",
      "requiredAmount",
      "approvalHash"
    ]
  },
  "TransactionReplaced": {
    "stage": "tracking",
    "retry": "track-linked-successor",
    "requiredContext": [
      "originalHash",
      "replacementHash",
      "reason"
    ]
  },
  "TransactionCancelled": {
    "stage": "tracking",
    "retry": "explicit-new-intent-only",
    "requiredContext": [
      "originalHash",
      "cancellationHash"
    ]
  },
  "TransactionFailed": {
    "stage": "receipt",
    "retry": "after-root-cause-review",
    "requiredContext": [
      "transactionHash",
      "receiptStatus",
      "blockNumber"
    ]
  },
  "TransactionTimeout": {
    "stage": "tracking",
    "retry": "continue-tracking-or-rebroadcast-exact-bytes",
    "requiredContext": [
      "transactionHash",
      "deadline",
      "lastCheckedBlock"
    ]
  },
  "TransactionReorged": {
    "stage": "confirmation",
    "retry": "resume-tracking",
    "requiredContext": [
      "transactionHash",
      "formerBlockHash",
      "detectionBlock"
    ]
  },
  "ReconciliationError": {
    "stage": "reconciliation",
    "retry": "workflow-specific",
    "requiredContext": [
      "transactionHash",
      "receiptBlock",
      "expectedOutcome",
      "observedOutcome"
    ]
  }
} as const;
