// Generated by scripts/generate-borrowing-package.ts. Do not edit.
// Canonical Contracts ABI/catalog and borrowing-formulas; sha256:3d4bf24e5983573209949a1fbf517c9ef95a296e572d1559dbe3729bb4edea20
export const BORROWING_CONSTANTS = Object.freeze({
  decimalPrecision: "1000000000000000000",
  nicrPrecision: "100000000000000000000",
  basisPoints: "10000",
  secondsInProtocolYear: "31556952",
  uint256Max: "115792089237316195423570985008687907853269984665640564039457584007913129639935",
});
