// Generated by scripts/generate-borrowing-package.ts. Do not edit.
// Canonical Contracts ABI/catalog and borrowing-formulas; sha256:b9240c19f9c4065eeeb6d842e5daa82e44ea4436033c7da18819350507fa0daf
export const BORROWING_CONSTANTS = Object.freeze({
  decimalPrecision: "1000000000000000000",
  nicrPrecision: "100000000000000000000",
  basisPoints: "10000",
  secondsInProtocolYear: "31556952",
  uint256Max: "115792089237316195423570985008687907853269984665640564039457584007913129639935",
});
