// Generated by scripts/generate/generate-borrowing-package.ts. Do not edit.
// Canonical Contracts ABI/catalog and borrowing-formulas; sha256:92da85bae50f64d0c92cf135f1e57c0ae0d5b31d2608df79b2ec1b83a6effb53
export const BORROWING_CONSTANTS = Object.freeze({
  decimalPrecision: "1000000000000000000",
  nicrPrecision: "100000000000000000000",
  basisPoints: "10000",
  secondsInProtocolYear: "31556952",
  uint256Max: "115792089237316195423570985008687907853269984665640564039457584007913129639935",
});
