// Generated by scripts/generate-model.ts. Do not edit.
// Canonical input: generator-input/synthetic-model.json
// Input digest: sha256:9c30fc7e5e440df546298d3d5abd927d4b13655d97556bce1aa048a308792877

export const SYNTHETIC_MODEL = {
  schemaVersion: 1,
  kind: "synthetic-reading",
  assetId: "synthetic-widget",
  decimals: 6,
} as const;
