import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const inputRelativePath = "generator-input/synthetic-model.json";
const inputPath = resolve(packageRoot, inputRelativePath);
const outputPath = resolve(packageRoot, "src/model.generated.ts");
assertInsidePackage(inputPath, "generator input");
assertInsidePackage(outputPath, "generated output");

const checkOnly = process.argv.slice(2).includes("--check");
const unknownArguments = process.argv.slice(2).filter((value) => value !== "--check");
if (unknownArguments.length > 0) {
  throw new Error(`unknown argument '${unknownArguments[0]}'`);
}

const inputBytes = await readFile(inputPath);
const model = parseModel(JSON.parse(inputBytes.toString("utf8")) as unknown);
const inputDigest = createHash("sha256").update(inputBytes).digest("hex");
const output = [
  "// Generated by scripts/generate-model.ts. Do not edit.",
  `// Canonical input: ${inputRelativePath}`,
  `// Input digest: sha256:${inputDigest}`,
  "",
  "export const SYNTHETIC_MODEL = {",
  `  schemaVersion: ${model.schemaVersion},`,
  `  kind: ${JSON.stringify(model.kind)},`,
  `  assetId: ${JSON.stringify(model.assetId)},`,
  `  decimals: ${model.decimals},`,
  "} as const;",
  "",
].join("\n");

if (checkOnly) {
  let current: string;
  try {
    current = await readFile(outputPath, "utf8");
  } catch (error) {
    throw new Error("generated model is missing; run pnpm generate", { cause: error });
  }
  if (current !== output) {
    throw new Error("generated model drifted; update the input or generator and regenerate");
  }
} else {
  await writeFile(outputPath, output, "utf8");
}

process.stdout.write(`Synthetic model is current (${inputDigest}).\n`);

interface SyntheticModel {
  readonly schemaVersion: 1;
  readonly kind: string;
  readonly assetId: string;
  readonly decimals: number;
}

function parseModel(value: unknown): SyntheticModel {
  const record = object(value, "synthetic model");
  if (record.schemaVersion !== 1) {
    throw new Error("synthetic model schemaVersion must be 1");
  }
  const kind = text(record.kind, "synthetic model kind");
  const assetId = text(record.assetId, "synthetic model assetId");
  const decimals = integer(record.decimals, "synthetic model decimals");
  if (decimals < 0 || decimals > 255) {
    throw new Error("synthetic model decimals must be from 0 through 255");
  }
  return { schemaVersion: 1, kind, assetId, decimals };
}

function object(value: unknown, label: string): Readonly<Record<string, unknown>> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

function text(value: unknown, label: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`${label} must be a non-empty string`);
  }
  return value;
}

function integer(value: unknown, label: string): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value)) {
    throw new Error(`${label} must be a safe integer`);
  }
  return value;
}

function assertInsidePackage(target: string, label: string): void {
  const relation = relative(packageRoot, target);
  if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`)) {
    throw new Error(`${label} escapes the package`);
  }
}
