// Generated by scripts/generate-bridges-package.ts. Do not edit.
// sha256:a812f5d1b802b845f0a506b465cba09d610abf89096d7831186a4bcd86289007
export const NTT_ROUTES = [
  {
    id: "wormhole-ntt-musd-mezo-to-ethereum",
    source: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "ethereum-mainnet",
      wormholeChainId: 2,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
  {
    id: "wormhole-ntt-musd-ethereum-to-mezo",
    source: {
      networkId: "ethereum-mainnet",
      wormholeChainId: 2,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
  {
    id: "wormhole-ntt-musd-mezo-to-base",
    source: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "base-mainnet",
      wormholeChainId: 30,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
  {
    id: "wormhole-ntt-musd-base-to-mezo",
    source: {
      networkId: "base-mainnet",
      wormholeChainId: 30,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
] as const;
export const NATIVE_ROUTES = [
  {
    id: "mezo-native-usdc-ethereum-to-mezo",
    direction: "inbound-to-mezo",
    source: {
      networkId: "ethereum-mainnet",
      contractId: "bridge.native-mezo-bridge",
      token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    },
    destination: {
      networkId: "mezo-mainnet",
      contractId: "bridge.native-assets-precompile",
      token: "0x04671c72aab5ac02a03c1098314b1bb6b560c197",
    },
    targetChain: null,
  },
  {
    id: "mezo-native-btc-mezo-to-ethereum",
    direction: "outbound-from-mezo",
    source: {
      networkId: "mezo-mainnet",
      contractId: "bridge.native-assets-precompile",
      token: "0x7b7c000000000000000000000000000000000000",
    },
    destination: {
      networkId: "ethereum-mainnet",
      contractId: "bridge.native-mezo-bridge",
      token: "0x18084fba666a33d37592fa2633fd49a74dd93a88",
    },
    targetChain: 0,
  },
] as const;
