// Generated by scripts/generate/generate-bridges-package.ts. Do not edit.
// sha256:8e1aeac02a46feb5181ae76903034854f9f69f666ebdee110f420142c3a82951
export const NTT_ROUTES = [
  {
    id: "wormhole-ntt-musd-mezo-to-ethereum",
    source: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "893d9275226a5019c7ad52628010228272d2124732d951a0ca376aded02b4107",
      decimals: 18,
      mode: 0,
    },
    destination: {
      networkId: "ethereum-mainnet",
      wormholeChainId: 2,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "ddfeb0e9ac8cf310aaa3fa4150fcca7fed33a31579df515f0041436360574441",
      decimals: 18,
      mode: 1,
    },
  },
  {
    id: "wormhole-ntt-musd-ethereum-to-mezo",
    source: {
      networkId: "ethereum-mainnet",
      wormholeChainId: 2,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "ddfeb0e9ac8cf310aaa3fa4150fcca7fed33a31579df515f0041436360574441",
      decimals: 18,
      mode: 1,
    },
    destination: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "893d9275226a5019c7ad52628010228272d2124732d951a0ca376aded02b4107",
      decimals: 18,
      mode: 0,
    },
  },
  {
    id: "wormhole-ntt-musd-mezo-to-base",
    source: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "893d9275226a5019c7ad52628010228272d2124732d951a0ca376aded02b4107",
      decimals: 18,
      mode: 0,
    },
    destination: {
      networkId: "base-mainnet",
      wormholeChainId: 30,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "2bd5ddb1e191345c82d7f824e2917f0f717316df3b86b1245680c678b2ec9417",
      decimals: 18,
      mode: 1,
    },
  },
  {
    id: "wormhole-ntt-musd-base-to-mezo",
    source: {
      networkId: "base-mainnet",
      wormholeChainId: 30,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "2bd5ddb1e191345c82d7f824e2917f0f717316df3b86b1245680c678b2ec9417",
      decimals: 18,
      mode: 1,
    },
    destination: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
      token: "0xdd468a1ddc392dcdbef6db6e34e89aa338f9f186",
      tokenCodeSha256: "893d9275226a5019c7ad52628010228272d2124732d951a0ca376aded02b4107",
      decimals: 18,
      mode: 0,
    },
  },
] as const;
export const NATIVE_ROUTES = [
  {
    id: "mezo-native-usdc-ethereum-to-mezo",
    direction: "inbound-to-mezo",
    source: {
      networkId: "ethereum-mainnet",
      contractId: "bridge.native-mezo-bridge",
      token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    },
    destination: {
      networkId: "mezo-mainnet",
      contractId: "bridge.native-assets-precompile",
      token: "0x04671c72aab5ac02a03c1098314b1bb6b560c197",
    },
    targetChain: null,
  },
  {
    id: "mezo-native-btc-mezo-to-ethereum",
    direction: "outbound-from-mezo",
    source: {
      networkId: "mezo-mainnet",
      contractId: "bridge.native-assets-precompile",
      token: "0x7b7c000000000000000000000000000000000000",
    },
    destination: {
      networkId: "ethereum-mainnet",
      contractId: "bridge.native-mezo-bridge",
      token: "0x18084fba666a33d37592fa2633fd49a74dd93a88",
    },
    targetChain: 0,
  },
] as const;
export const NATIVE_CLIENT = {
  reportedVersionPrefix: "Mezod/13.0.0/",
  mintAuthority: "0x17f29b073143d8cd97b5bbe492bdeffec1c5fee5",
  blockedRecipients: [
    "0xf1829676db577682e944fc3493d451b67ff3e29f",
    "0x70963e33ab0c3fcd4d195e3545795885f13140c8",
    "0x603871c2ddd41c26ee77495e2e31e6de7f9957e0",
    "0x17f29b073143d8cd97b5bbe492bdeffec1c5fee5",
  ],
} as const;
