// Generated by scripts/generate-bridges-package.ts. Do not edit.
// sha256:7a73a56109948d2c48275a4297bdfbfd04e340fad5f132ac59a6e6be49d79d1d
export const NTT_ROUTES = [
  {
    id: "wormhole-ntt-musd-mezo-to-ethereum",
    source: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "ethereum-mainnet",
      wormholeChainId: 2,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
  {
    id: "wormhole-ntt-musd-ethereum-to-mezo",
    source: {
      networkId: "ethereum-mainnet",
      wormholeChainId: 2,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
  {
    id: "wormhole-ntt-musd-mezo-to-base",
    source: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "base-mainnet",
      wormholeChainId: 30,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
  {
    id: "wormhole-ntt-musd-base-to-mezo",
    source: {
      networkId: "base-mainnet",
      wormholeChainId: 30,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
    destination: {
      networkId: "mezo-mainnet",
      wormholeChainId: 50,
      managerId: "bridge.musd-ntt-manager",
      transceiverId: "bridge.musd-wormhole-transceiver",
    },
  },
] as const;
