import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  display,
  object,
  objects,
  parseJson,
  scalar,
  text,
  texts,
  values,
  type JsonObject,
} from "./lib/json.ts";
import { loadKnowledgeModule, resolveKnowledgeResource } from "./lib/knowledge-reference.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknown = process.argv.slice(2).filter((value) => value !== "--check");
if (unknown.length > 0) throw new Error(`unknown argument '${unknown[0]}'`);

function cell(value: unknown): string {
  return display(value, "table cell").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers: unknown[], rows: unknown[][]): string {
  return [
    `| ${headers.map(cell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

const module = await loadKnowledgeModule(repositoryRoot, "workflows/bridges");
const generated = module.index.resources.find((resource) => resource.id === "bridge-reference");
if (generated?.role !== "generated")
  throw new Error("bridge-reference generated resource is missing");
const outputPath = resolve(module.directory, generated.path);
const relation = relative(module.directory, outputPath);
if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`))
  throw new Error("bridge reference output escapes its module");

const digest = createHash("sha256");
digest.update(await readFile(module.indexPath));
const byId = new Map<string, JsonObject>();
for (const reference of objects(generated.generatedFrom, "bridge reference inputs")) {
  const moduleId = text(reference.moduleId, "bridge reference module ID");
  const resourceId = text(reference.resourceId, "bridge reference resource ID");
  const resolved = await resolveKnowledgeResource(repositoryRoot, reference);
  const bytes = await readFile(resolved.path);
  digest.update(`${moduleId}:${resourceId}\0`);
  digest.update(bytes);
  digest.update("\0");
  byId.set(resourceId, object(parseJson(bytes.toString("utf8"), resourceId), resourceId));
}

const providers = required("bridge-providers");
const assets = required("bridge-assets");
const routes = required("bridge-routes");
const contractRoles = required("bridge-contract-roles");
const ntt = required("bridge-ntt-lifecycle");
const native = required("bridge-native-lifecycle");
const nttEvidence = required("bridge-musd-ntt-evidence");
const nativeEvidence = required("bridge-native-evidence");
const inputDigest = digest.digest("hex");
const extensions = object(module.index.extensions, "bridge module extensions");

const output = [
  "<!-- Generated by scripts/generate-bridge-reference.ts. Do not edit. -->",
  "",
  "# Bridge evidence reference",
  "",
  "This is a deterministic projection of indexed canonical knowledge, not an independent authority.",
  "",
  "- Module: `workflows/bridges`",
  `- Support: \`${display(module.index.supportStatus, "module support")}\``,
  `- Review: \`${display(module.index.reviewStatus, "module review")}\``,
  `- Verified: \`${display(module.index.verifiedAt, "module verification date")}\``,
  `- Review after: \`${display(module.index.reviewAfter, "module review date")}\``,
  `- Input digest: \`sha256:${inputDigest}\``,
  "",
  "## Inventory",
  "",
  table(
    ["Resource", "Count"],
    [
      ["Providers", values(providers.records, "providers").length],
      ["Assets", values(assets.records, "assets").length],
      ["Route candidates", values(routes.records, "routes").length],
      ["Canonical contract roles", values(contractRoles.records, "contract roles").length],
      [
        "Deployment snapshots",
        values(nttEvidence.deploymentObservations, "NTT deployments").length +
          values(nativeEvidence.deploymentObservations, "native deployments").length,
      ],
      [
        "Completed transfer traces",
        values(nttEvidence.completedTransfers, "NTT transfers").length +
          values(nativeEvidence.completedTransfers, "native transfers").length,
      ],
    ],
  ),
  "",
  "## Evidence-backed route candidates",
  "",
  table(
    ["Route", "Provider", "Source representation", "Destination representation", "Status"],
    objects(routes.records, "bridge routes").map((route) => [
      scalar(route.id, "route ID"),
      scalar(route.providerId, "route provider"),
      scalar(route.sourceRepresentationId, "route source representation"),
      scalar(route.destinationRepresentationId, "route destination representation"),
      scalar(route.status, "route status"),
    ]),
  ),
  "",
  "## Canonical contract references",
  "",
  table(
    ["Role", "Provider", "Network", "Deployment record", "ABI record"],
    objects(contractRoles.records, "bridge contract roles").map((role) => {
      const deploymentReference = object(role.deploymentReference, "deployment reference");
      const abiReference = object(role.abiReference, "ABI reference");
      return [
        scalar(role.role, "contract role"),
        scalar(role.providerId, "role provider"),
        scalar(role.networkId, "role network"),
        scalar(deploymentReference.recordId, "deployment record ID"),
        scalar(abiReference.recordId, "ABI record ID"),
      ];
    }),
  ),
  "",
  "## Provider completion rules",
  "",
  table(
    ["Provider", "Terminal success"],
    objects(providers.records, "bridge providers").map((provider) => [
      scalar(provider.id, "provider ID"),
      scalar(provider.terminalSuccessRule, "provider terminal success rule"),
    ]),
  ),
  "",
  `MUSD NTT completion is the \`${display(completedNttState().evidence, "NTT completion evidence")}\`.`,
  "",
  `Native inbound and outbound completion remain direction-specific across ${values(native.directions, "native directions").length} models. An inbound system receipt or sequence advance alone is not ERC-20 delivery proof.`,
  "",
  "## Production boundary",
  "",
  "bridge evidence review accepted the bounded provider, asset, route, lifecycle, and evidence model plus the current generation-6 Assets Bridge deployment. All route records remain evidence-verified but unsupported; registry and knowledge acceptance create no route, relayer, quote, or writer support. Dated evidence addresses are checked observation coordinates, not duplicate owners.",
  "",
  "Remaining blockers:",
  "",
  ...texts(extensions.blockers, "bridge blockers").map((blocker) => `- ${blocker}`),
  "",
].join("\n");

if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("generated/reference.md is missing; run the generator without --check");
  }
  if (current !== output) throw new Error("workflows/bridges generated reference drifted");
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

process.stdout.write(`workflows/bridges reference is current (${inputDigest}).\n`);

function required(resourceId: string): JsonObject {
  const value = byId.get(resourceId);
  if (value === undefined) throw new Error(`required resource '${resourceId}' is missing`);
  return value;
}

function completedNttState(): JsonObject {
  const state = objects(ntt.states, "NTT states").find((candidate) => candidate.id === "completed");
  if (state === undefined) throw new Error("completed NTT state is missing");
  return state;
}
