import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

import { buildContractsPackageFile } from "./lib/foundational-package-generation.ts";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
if (args.some((arg) => arg !== "--check"))
  throw new Error("usage: generate-borrowing-package.ts [--check]");
const digest = createHash("sha256");
// This validates catalog lifecycles, deployment ranges and every ABI digest.
digest.update((await buildContractsPackageFile(root)).digest);
const source = await loadKnowledgeReference(root, {
  moduleId: "contracts",
  resourceId: "abi.musd.borrower-operations",
});
if (!Array.isArray(source.document)) throw new Error("BorrowerOperations ABI must be an array");
const names = [
  "openTrove",
  "addColl",
  "withdrawColl",
  "withdrawMUSD",
  "repayMUSD",
  "adjustTrove",
  "closeTrove",
  "refinance",
  "claimCollateral",
];
const entries = source.document.filter((value: unknown) => {
  const entry = object(value);
  return entry.type === "function" && typeof entry.name === "string" && names.includes(entry.name);
});
if (
  entries.length !== names.length ||
  new Set(entries.map((entry: unknown) => object(entry).name)).size !== names.length
)
  throw new Error("curated borrower operation ABI mismatch");
digest.update(await readFile(source.path));
const formulas = await loadKnowledgeReference(root, {
  moduleId: "protocols/musd/borrowing",
  resourceId: "borrowing-formulas",
});
const catalog = object(formulas.document);
if (catalog.status !== "verified" || catalog.reviewStatus !== "accepted")
  throw new Error("unaccepted borrowing formulas");
const constants = object(catalog.constants);
for (const value of Object.values(constants))
  if (typeof value !== "string" || !/^[1-9][0-9]*$/.test(value))
    throw new Error("invalid formula constant");
digest.update(await readFile(formulas.path));
const identities: Record<string, unknown> = {};
for (const id of [
  "borrower-operations",
  "trove-manager",
  "token",
  "active-pool",
  "default-pool",
  "interest-rate-manager",
  "governable-variables",
  "hint-helpers",
  "sorted-troves",
  "coll-surplus-pool",
  "price-feed",
  "gas-pool",
  "pcv",
]) {
  const contractId = `musd.${id}`;
  const deployment = await loadKnowledgeReference(root, {
    moduleId: "contracts",
    resourceId: "contract-deployments",
    recordId: `${contractId}@mezo-mainnet`,
  });
  const record = object(deployment.value);
  const runtime = object(record.runtime);
  const proxy = record.proxy === null ? null : object(record.proxy);
  identities[contractId] = {
    addressCodeSha256: runtime.addressCodeSha256,
    implementationCodeSha256: runtime.implementationCodeSha256 ?? null,
    implementationSlot: proxy?.implementationSlot ?? null,
  };
  digest.update(await readFile(deployment.path));
}
const header = `// Generated by scripts/generate-borrowing-package.ts. Do not edit.\n// Canonical Contracts ABI/catalog and borrowing-formulas; sha256:${digest.digest("hex")}\n`;
await output(
  "packages/contracts/src/operations.generated.ts",
  `${header}import type { ContractAbiEntry } from "./registry.ts";\nimport type { ContractRuntimeIdentity } from "./operations.ts";\nexport const BORROWER_OPERATION_ABI: readonly ContractAbiEntry[] = ${JSON.stringify(entries)};\nexport const BORROWING_RUNTIME_IDENTITIES: Readonly<Record<string, ContractRuntimeIdentity>> = ${JSON.stringify(identities)};\n`,
);
await output(
  "packages/protocols/musd-borrowing/src/constants.generated.ts",
  `${header}export const BORROWING_CONSTANTS = Object.freeze(${JSON.stringify(constants)});\n`,
);

function object(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value))
    throw new Error("expected record");
  return value as Record<string, unknown>;
}
async function output(path: string, sourceText: string): Promise<void> {
  const text = await format(sourceText, {
    parser: "typescript",
    ...(JSON.parse(await readFile(resolve(root, ".prettierrc.json"), "utf8")) as Record<
      string,
      unknown
    >),
  });
  if (args.includes("--check")) {
    if ((await readFile(resolve(root, path), "utf8")) !== text)
      throw new Error(`generated drift: ${path}`);
  } else await writeFile(resolve(root, path), text);
}
