import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  display,
  object,
  objects,
  parseJson,
  scalar,
  text,
  texts,
  type JsonObject,
} from "./lib/json.ts";
import { loadKnowledgeModule, resolveKnowledgeResource } from "./lib/knowledge-reference.ts";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknownArguments = process.argv.slice(2).filter((argument) => argument !== "--check");

if (unknownArguments.length > 0) {
  throw new Error(`unknown argument '${unknownArguments[0]}'`);
}

function escapeCell(value: unknown): string {
  return display(value, "table cell").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers: unknown[], rows: unknown[][]): string {
  return [
    `| ${headers.map(escapeCell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`),
  ].join("\n");
}

const module = await loadKnowledgeModule(repositoryRoot, "networks");
const generatedResource = module.index.resources.find(
  (resource) => resource.id === "network-reference",
);
if (generatedResource?.role !== "generated") {
  throw new Error("network-reference generated resource is missing from the Networks index");
}
const outputPath = resolve(module.directory, generatedResource.path);
const outputRelation = relative(module.directory, outputPath);
if (outputRelation === "" || outputRelation === ".." || outputRelation.startsWith(`..${sep}`)) {
  throw new Error("network-reference output escapes the Networks module");
}
const inputHash = createHash("sha256");
inputHash.update(await readFile(module.indexPath));

const inputs: { reference: JsonObject; document: JsonObject }[] = [];
const generatedFrom = objects(generatedResource.generatedFrom, "network reference inputs");
for (const reference of generatedFrom) {
  const moduleId = text(reference.moduleId, "network reference module ID");
  const resourceId = text(reference.resourceId, "network reference resource ID");
  const resolved = await resolveKnowledgeResource(repositoryRoot, reference);
  const bytes = await readFile(resolved.path);
  inputHash.update(`${moduleId}:${resourceId}\0`);
  inputHash.update(bytes);
  inputHash.update("\0");
  inputs.push({
    reference,
    document: object(parseJson(bytes.toString("utf8"), resourceId), resourceId),
  });
}

const inputDigest = inputHash.digest("hex");
const byResource = new Map(
  inputs.map((input) => [text(input.reference.resourceId, "resource ID"), input.document]),
);
const scope = object(module.index.scope, "network module scope");
const networks = texts(scope.networkIds, "network IDs").map(required);
const endpoints = required("rpc-endpoints");
const sources = required("network-sources");

const lines = [
  "<!-- Generated by scripts/generate-network-reference.ts. Do not edit. -->",
  "",
  "# MDK network reference",
  "",
  "This is a deterministic human-readable projection of the canonical Networks",
  "module. Resolve exact values and evidence through `knowledge/networks/index.json`;",
  "this page is not an independent authority. Its support scope is the lifecycle",
  "state shown below and remains bounded by each record's limitations and freshness.",
  "",
  `- Input digest: \`sha256:${inputDigest}\``,
  `- Module support: \`${display(module.index.supportStatus, "module support")}\``,
  `- Module review: \`${display(module.index.reviewStatus, "module review")}\``,
  `- Module review after: \`${display(module.index.reviewAfter, "module review date")}\``,
  "- Canonical inputs: " +
    generatedFrom
      .map(
        (reference) =>
          `\`${text(reference.moduleId, "input module ID")}:${text(reference.resourceId, "input resource ID")}\``,
      )
      .join(", "),
  "",
  "## Networks",
  "",
  table(
    [
      "ID",
      "Display name",
      "Profile",
      "EVM chain ID",
      "Cosmos chain ID",
      "Native currency",
      "Explorer",
      "Support",
      "Review",
      "Verified",
      "Review after",
    ],
    networks.map((network) => {
      const values = object(network.values, "network values");
      const nativeCurrency = object(values.nativeCurrency, "native currency");
      const explorer = object(values.explorer, "network explorer");
      const cosmosDenom =
        values.cosmosChainId === undefined
          ? ""
          : `; Cosmos denom ${display(nativeCurrency.cosmosEvmDenom, "Cosmos denomination")}`;
      return [
        scalar(network.id, "network ID"),
        scalar(values.displayName, "network display name"),
        scalar(values.profile, "network profile"),
        scalar(values.evmChainId, "EVM chain ID"),
        values.cosmosChainId === undefined
          ? "n/a"
          : scalar(values.cosmosChainId, "Cosmos chain ID"),
        `${display(nativeCurrency.symbol, "currency symbol")} (${display(nativeCurrency.decimals, "currency decimals")} decimals${cosmosDenom})`,
        `[${display(explorer.name, "explorer name")}](${display(explorer.url, "explorer URL")})`,
        scalar(network.supportStatus, "network support"),
        scalar(network.reviewStatus, "network review"),
        scalar(network.verifiedAt, "network verification date"),
        scalar(network.reviewAfter, "network review date"),
      ];
    }),
  ),
  "",
  "Stable chain identity does not imply that a provider is currently available",
  "or supports an optional RPC capability. Proposed records are not MDK support",
  "promises, and Ethereum/Base select no RPC endpoint.",
  "",
  "## Published RPC endpoints",
  "",
  table(
    [
      "ID",
      "Network",
      "Provider",
      "Transport",
      "URL",
      "Publication",
      "Support",
      "Observed status",
      "Last verified",
    ],
    objects(endpoints.records, "RPC endpoints").map((endpoint) => [
      scalar(endpoint.id, "endpoint ID"),
      scalar(endpoint.networkId, "endpoint network"),
      scalar(endpoint.provider, "endpoint provider"),
      scalar(endpoint.transport, "endpoint transport"),
      scalar(endpoint.url, "endpoint URL"),
      scalar(endpoint.publicationStatus, "endpoint publication"),
      scalar(endpoint.supportStatus, "endpoint support"),
      scalar(endpoint.operationalStatus, "endpoint operational status"),
      scalar(endpoint.lastVerifiedAt, "endpoint verification date"),
    ]),
  ),
  "",
  `Endpoint observations must be reviewed after \`${display(endpoints.reviewAfter, "endpoint review date")}\` or before sensitive use.`,
  "A failed point-in-time check is not proof of permanent unavailability; a",
  "successful check is not an uptime or complete-compatibility guarantee.",
  "",
  "## Source catalog",
  "",
  table(
    ["Source ID", "Kind", "Retrieved", "Pinned revision"],
    objects(sources.sources, "network sources").map((source) => [
      scalar(source.id, "source ID"),
      scalar(source.kind, "source kind"),
      scalar(source.retrievedAt, "source retrieval date"),
      source.commit === undefined
        ? "bounded local observation"
        : scalar(source.commit, "source commit"),
    ]),
  ),
  "",
];

const output = `${lines.join("\n").trimEnd()}\n`;
if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("generated network reference is missing; run the generator without --check");
  }
  if (current !== output) throw new Error("generated network reference drifted; regenerate it");
  process.stdout.write(`Network reference is current (${inputDigest}).\n`);
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  process.stdout.write(`Generated ${generatedResource.path} (${inputDigest}).\n`);
}

function required(resourceId: string): JsonObject {
  const value = byResource.get(resourceId);
  if (value === undefined) {
    throw new Error(`network-reference generatedFrom is missing '${resourceId}'`);
  }
  return value;
}
