import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknown = process.argv.slice(2).filter((value) => value !== "--check");
if (unknown.length > 0) throw new Error(`unknown argument '${unknown[0]}'`);

const [stateResult, errorResult] = await Promise.all([
  loadKnowledgeReference(repositoryRoot, {
    moduleId: "workflows/transactions",
    resourceId: "transaction-state-machine",
  }),
  loadKnowledgeReference(repositoryRoot, {
    moduleId: "workflows/transactions",
    resourceId: "transaction-errors",
  }),
]);
const outputPath = resolve(repositoryRoot, "packages", "core", "src", "model.generated.ts");
const packageDirectory = resolve(repositoryRoot, "packages", "core");
const relation = relative(packageDirectory, outputPath);
if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`)) {
  throw new Error("generated core model output escapes packages/core");
}

type JsonObject = Record<string, unknown>;

const stateDocument = object(stateResult.document, "transaction state document");
const errorDocument = object(errorResult.document, "transaction error document");
const states = objects(stateDocument.states, "transaction states").map((state) => ({
  id: text(state.id, "transaction state ID"),
  terminal: boolean(state.terminal, "transaction state terminal flag"),
  actionHashRequired: boolean(state.actionHashRequired, "transaction state action-hash flag"),
  approvalHashRequired:
    state.approvalHashRequired === undefined
      ? false
      : boolean(state.approvalHashRequired, "transaction state approval-hash flag"),
  successLevel: text(state.successLevel, "transaction state success level"),
}));
const transitions = objects(stateDocument.transitions, "transaction transitions").map(
  (transition) => ({
    from: text(transition.from, "transaction transition source"),
    event: text(transition.event, "transaction transition event"),
    to: text(transition.to, "transaction transition target"),
  }),
);
const errors = Object.fromEntries(
  objects(errorDocument.errors, "transaction errors").map((error) => [
    text(error.id, "transaction error ID"),
    {
      stage: text(error.stage, "transaction error stage"),
      retry: text(error.retry, "transaction error retry rule"),
      requiredContext: strings(error.requiredContext, "transaction error required context"),
    },
  ]),
);
const inputDigest = createHash("sha256")
  .update(await readFile(stateResult.path))
  .update("\0")
  .update(await readFile(errorResult.path))
  .digest("hex");
const output = [
  "// Generated by scripts/generate-core-transaction-model.ts. Do not edit.",
  `// Input digest: sha256:${inputDigest}`,
  "",
  `export const GENERATED_TRANSACTION_STATES = ${JSON.stringify(states, null, 2)} as const;`,
  "",
  `export const GENERATED_TRANSACTION_TRANSITIONS = ${JSON.stringify(transitions, null, 2)} as const;`,
  "",
  `export const GENERATED_ERROR_DEFINITIONS = ${JSON.stringify(errors, null, 2)} as const;`,
  "",
].join("\n");

if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("packages/core/src/model.generated.ts is missing; run the generator");
  }
  if (current !== output) throw new Error("packages/core generated transaction model drifted");
} else {
  await writeFile(outputPath, output, "utf8");
}

process.stdout.write(`Core transaction model is current (${inputDigest}).\n`);

function object(value: unknown, label: string): JsonObject {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
  return value as JsonObject;
}

function objects(value: unknown, label: string): JsonObject[] {
  if (!Array.isArray(value)) throw new Error(`${label} must be an array`);
  return value.map((item, index) => object(item as unknown, `${label}[${index}]`));
}

function text(value: unknown, label: string): string {
  if (typeof value !== "string") throw new Error(`${label} must be a string`);
  return value;
}

function boolean(value: unknown, label: string): boolean {
  if (typeof value !== "boolean") throw new Error(`${label} must be a boolean`);
  return value;
}

function strings(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || !value.every((item) => typeof item === "string")) {
    throw new Error(`${label} must be an array of strings`);
  }
  return value;
}
