import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";
import { object, objects, text } from "./lib/json.ts";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
if (process.argv.slice(2).some((arg) => arg !== "--check"))
  throw new Error("usage: generate-incentives-package.ts [--check]");
const digest = createHash("sha256");
async function resource(resourceId: string) {
  const loaded = await loadKnowledgeReference(root, {
    moduleId: "protocols/incentives",
    resourceId,
  });
  digest.update(await readFile(loaded.path));
  const value = object(loaded.document, resourceId);
  if (value.status !== "verified" || value.reviewStatus !== "accepted")
    throw new Error("incentives lifecycle differs");
  return value;
}
const locks = await resource("incentives-locks"),
  boost = await resource("incentives-boost"),
  voting = await resource("incentives-voting"),
  fixtures = await resource("incentives-formula-fixtures"),
  topology = await resource("incentives-mainnet-topology"),
  roles = await resource("incentives-contract-roles");
const epoch = object(voting.epoch, "epoch"),
  epochFixture = objects(fixtures.records, "fixtures").find((row) => row.id === "epoch-zero");
if (!epochFixture) throw new Error("canonical epoch boundary fixture missing");
const epochZero = object(epochFixture.expected, "epoch boundaries"),
  week = text(epoch.lengthSeconds, "week");
const escrows: Record<string, unknown>[] = [];
for (const asset of objects(locks.assets, "escrows")) {
  const row = objects(topology.contracts, "topology contracts").find(
      (row) => row.role === asset.id,
    ),
    role = objects(roles.records, "roles").find((row) => row.id === asset.id);
  if (!row || !role) throw new Error("escrow identity missing");
  const deploymentReference = object(role.deploymentReference, "deployment"),
    recordId = text(deploymentReference.recordId, "deployment id"),
    state = object(object(row.storageObservations, "storage").maxLockTime, "max time"),
    references = object(row.observedReferences, "references");
  const deployment = await loadKnowledgeReference(root, {
    moduleId: "contracts",
    resourceId: "contract-deployments",
    recordId,
  });
  digest.update(await readFile(deployment.path));
  if (
    object(deployment.value, "deployment").address !== row.address ||
    state.decodedSeconds !== asset.maxLockSeconds
  )
    throw new Error("escrow topology and registry differ");
  escrows.push({
    role: asset.id,
    contractId: object(deployment.value, "deployment").contractId,
    decimals: asset.decimals,
    maxLockSeconds: asset.maxLockSeconds,
    maxLockSlot: `0x${BigInt(text(state.slot, "slot")).toString(16).padStart(64, "0")}`,
    underlying: references.underlyingToken,
    boostable: asset.boostable,
  });
}
const model = {
  lockConstants: locks.constants,
  boostConstants: boost.constants,
  week,
  voteStartOffset: epochZero.voteStart,
  voteEndOffset: (
    BigInt(text(epochZero.next, "next")) - BigInt(text(epochZero.voteEnd, "end"))
  ).toString(),
  escrows,
};
const output = await format(
  `// Generated by scripts/generate-incentives-package.ts. Do not edit.\n// sha256:${digest.digest("hex")}\nexport const INCENTIVES_MODEL = ${JSON.stringify(model)} as const;\n`,
  {
    parser: "typescript",
    ...object(JSON.parse(await readFile(resolve(root, ".prettierrc.json"), "utf8")), "prettier"),
  },
);
const path = resolve(root, "packages/protocols/incentives/src/model.generated.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(path, "utf8")) !== output) throw new Error("incentives model drift");
} else await writeFile(path, output);
