import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  display,
  object,
  objects,
  parseJson,
  scalar,
  text,
  texts,
  values,
  type JsonObject,
} from "./lib/json.ts";
import { loadKnowledgeModule, resolveKnowledgeResource } from "./lib/knowledge-reference.ts";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknownArguments = process.argv.slice(2).filter((argument) => argument !== "--check");

if (unknownArguments.length > 0) {
  throw new Error(`unknown argument '${unknownArguments[0]}'`);
}

function escapeCell(value: unknown): string {
  return display(value, "table cell").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers: unknown[], rows: unknown[][]): string {
  return [
    `| ${headers.map(escapeCell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`),
  ].join("\n");
}

function recordId(reference: unknown): string {
  return text(object(reference, "knowledge reference").recordId, "knowledge reference record ID");
}

const module = await loadKnowledgeModule(repositoryRoot, "contracts");
const generatedResource = module.index.resources.find(
  (resource) => resource.id === "contract-reference",
);
if (generatedResource?.role !== "generated") {
  throw new Error("contract-reference generated resource is missing from the Contracts index");
}

const outputPath = resolve(module.directory, generatedResource.path);
const outputRelation = relative(module.directory, outputPath);
if (outputRelation === "" || outputRelation === ".." || outputRelation.startsWith(`..${sep}`)) {
  throw new Error("contract-reference output escapes the Contracts module");
}

const inputHash = createHash("sha256");
inputHash.update(await readFile(module.indexPath));
const inputs: { reference: JsonObject; document: JsonObject }[] = [];
for (const reference of objects(generatedResource.generatedFrom, "contract reference inputs")) {
  const moduleId = text(reference.moduleId, "contract reference module ID");
  const resourceId = text(reference.resourceId, "contract reference resource ID");
  const resolved = await resolveKnowledgeResource(repositoryRoot, reference);
  const bytes = await readFile(resolved.path);
  inputHash.update(`${moduleId}:${resourceId}\0`);
  inputHash.update(bytes);
  inputHash.update("\0");
  inputs.push({
    reference,
    document: object(parseJson(bytes.toString("utf8"), resourceId), resourceId),
  });
}

const inputDigest = inputHash.digest("hex");
const byResource = new Map(
  inputs.map((input) => [text(input.reference.resourceId, "input resource ID"), input.document]),
);
const deployments = required("contract-deployments");
const abis = required("contract-abis");
const sources = required("contract-sources");
const evidence = required("contract-probes-2026-08-18");
const evidenceSets = inputs
  .filter(({ document }) => document.kind === "contract-observation-set")
  .map(({ document }) => document);
const evidenceObservationCount = evidenceSets.reduce(
  (count, document) => count + values(document.observations, "evidence observations").length,
  0,
);
const deploymentRecords = objects(deployments.records, "contract deployments");
const abiRecords = objects(abis.records, "contract ABIs");

const lines = [
  "<!-- Generated by scripts/generate-contract-reference.ts. Do not edit. -->",
  "",
  "# Mezo contract registry reference",
  "",
  "This deterministic page projects the canonical Contracts module for human review.",
  "Resolve exact records, artifacts, and evidence through `knowledge/contracts/index.json`;",
  "this page is not an independent address/ABI authority or support promise.",
  "",
  `- Input digest: \`sha256:${inputDigest}\``,
  `- Module support: \`${display(module.index.supportStatus, "module support")}\``,
  `- Module review: \`${display(module.index.reviewStatus, "module review")}\``,
  `- Module review after: \`${display(module.index.reviewAfter, "module review date")}\``,
  `- Contracts: ${abiRecords.length}`,
  `- Deployments: ${deploymentRecords.length}`,
  `- Full ABI artifacts: ${abiRecords.length}`,
  `- Evidence observations: ${evidenceObservationCount}`,
  "",
  "An open validity range means no supersession was observed at the verification block;",
  "it does not make a deployment immutable. Re-verify after an upgrade, after the review",
  "date, or before protocol-sensitive use.",
  "",
  "## Deployments",
  "",
  table(
    [
      "Contract ID",
      "Network",
      "Address",
      "Type",
      "Provenance class",
      "Current implementation",
      "Current code from block",
      "Status",
      "Support",
      "Review",
      "Evidence record",
    ],
    deploymentRecords.map((deployment) => [
      scalar(deployment.contractId, "deployment contract ID"),
      scalar(deployment.networkId, "deployment network"),
      scalar(deployment.address, "deployment address"),
      scalar(deployment.contractType, "deployment type"),
      scalar(deployment.provenanceClass, "deployment provenance"),
      currentImplementation(deployment),
      scalar(
        object(
          object(deployment.validity, "deployment validity").currentCodeFrom,
          "current-code boundary",
        ).blockNumber,
        "current-code block",
      ),
      scalar(deployment.status, "deployment status"),
      scalar(deployment.supportStatus, "deployment support"),
      scalar(deployment.reviewStatus, "deployment review"),
      recordId(deployment.evidenceReference),
    ]),
  ),
  "",
  "## Proxy implementation history",
  "",
  "Present operations default to the latest verified open generation. Closed generations",
  "remain coordinate-scoped history and do not inherit the current ABI.",
  "",
  table(
    [
      "Contract ID",
      "Network",
      "Proxy",
      "Implementation",
      "From block",
      "Until block (exclusive)",
      "Generation",
      "ABI scope",
    ],
    deploymentRecords.flatMap((deployment) =>
      implementationHistory(deployment).map((generation, index, history) => {
        const current = index === history.length - 1;
        const effectiveFrom = object(generation.effectiveFrom, "implementation start");
        const effectiveUntil = generation.effectiveUntilExclusive;
        return [
          scalar(deployment.contractId, "deployment contract ID"),
          scalar(deployment.networkId, "deployment network"),
          scalar(deployment.address, "deployment address"),
          scalar(generation.implementationAddress, "implementation address"),
          scalar(effectiveFrom.blockNumber, "implementation start block"),
          effectiveUntil === null
            ? "open"
            : scalar(
                object(effectiveUntil, "implementation end").blockNumber,
                "implementation end block",
              ),
          current ? "current default" : "historical",
          current ? "canonical current ABI" : "coordinate-scoped; no current-ABI inheritance",
        ];
      }),
    ),
  ),
  "",
  "## Full ABI artifacts",
  "",
  table(
    [
      "Contract ID",
      "Networks",
      "Provenance class",
      "Entries",
      "Artifact resource",
      "Semantic SHA-256",
      "Source record",
      "Support",
      "Review",
    ],
    abiRecords.map((abi) => [
      scalar(abi.contractId, "ABI contract ID"),
      texts(abi.intendedNetworkIds, "ABI networks").join(", "),
      scalar(abi.provenanceClass, "ABI provenance"),
      scalar(abi.entryCount, "ABI entry count"),
      `contracts:${text(object(abi.artifactReference, "ABI artifact reference").resourceId, "ABI artifact resource ID")}`,
      scalar(abi.abiSemanticSha256, "ABI semantic digest"),
      recordId(abi.sourceReference),
      scalar(abi.supportStatus, "ABI support"),
      scalar(abi.reviewStatus, "ABI review"),
    ]),
  ),
  "",
  "## Sources",
  "",
  table(
    ["Source ID", "Kind", "Pinned commit", "Retrieved"],
    objects(sources.sources, "contract sources").map((source) => [
      scalar(source.id, "source ID"),
      scalar(source.kind, "source kind"),
      source.commit === undefined ? "bounded observation" : scalar(source.commit, "source commit"),
      source.retrievedAt === undefined
        ? "pinned source"
        : scalar(source.retrievedAt, "source retrieval date"),
    ]),
  ),
  "",
  "## Evidence window",
  "",
  `- Observed from: \`${display(evidence.observedFrom, "evidence start")}\``,
  `- Observed through: \`${display(evidence.observedThrough, "evidence end")}\``,
  `- Review after: \`${display(evidence.reviewAfter, "evidence review date")}\``,
  `- Network snapshots: ${objects(evidence.networkSnapshots, "network snapshots")
    .map(
      (snapshot) =>
        `${display(snapshot.networkId, "snapshot network")} at block ${display(snapshot.blockNumber, "snapshot block")}`,
    )
    .join("; ")}`,
  "",
];

const output = `${lines.join("\n").trimEnd()}\n`;
if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("generated contract reference is missing; run the generator without --check");
  }
  if (current !== output) throw new Error("generated contract reference drifted; regenerate it");
  process.stdout.write(`Contract reference is current (${inputDigest}).\n`);
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  process.stdout.write(`Generated ${generatedResource.path} (${inputDigest}).\n`);
}

function required(resourceId: string): JsonObject {
  const value = byResource.get(resourceId);
  if (value === undefined) throw new Error(`contract reference is missing '${resourceId}'`);
  return value;
}

function currentImplementation(deployment: JsonObject): string | number | boolean | null {
  if (deployment.proxy === null) return "direct";
  return scalar(
    object(deployment.proxy, "deployment proxy").currentImplementationAddress,
    "current implementation address",
  );
}

function implementationHistory(deployment: JsonObject): JsonObject[] {
  if (deployment.proxy === null) return [];
  return objects(
    object(deployment.proxy, "deployment proxy").implementationHistory,
    "implementation history",
  );
}
