import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";
import { object, objects, text } from "./lib/json.ts";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
if (process.argv.slice(2).some((arg) => arg !== "--check"))
  throw new Error("usage: generate-pools-package.ts [--check]");
const digest = createHash("sha256");
async function resource(moduleId: string, resourceId: string) {
  const loaded = await loadKnowledgeReference(root, { moduleId, resourceId });
  digest.update(await readFile(loaded.path));
  return object(loaded.document, resourceId);
}
const profile = await resource("contracts", "musdc-token-runtime"),
  market = await resource("protocols/lending/musdc", "musdc-lending-fixed-block-state");
if (
  profile.status !== "verified" ||
  profile.supportStatus !== "proposed" ||
  profile.reviewStatus !== "pending-qualified-review" ||
  profile.tokenAddress !==
    text(object(market.market, "market").loanToken, "loan token").toLowerCase()
)
  throw new Error("invalid mUSDC writer asset profile");
for (const entry of objects(profile.artifacts, "artifacts")) {
  const loaded = await loadKnowledgeReference(root, entry.reference);
  const bytes = await readFile(loaded.path);
  digest.update(bytes);
  if (createHash("sha256").update(bytes).digest("hex") !== entry.sha256)
    throw new Error("token artifact digest mismatch");
}
const proxy = await resource("contracts", "musdc-token-proxy-explorer"),
  implementation = await resource("contracts", "musdc-token-implementation-explorer"),
  probe = await resource("contracts", "musdc-token-runtime-probe");
const hash = (value: unknown) => {
  const code = text(value, "bytecode");
  if (!/^0x(?:[a-fA-F0-9]{2})+$/.test(code)) throw new Error("invalid bytecode");
  return createHash("sha256")
    .update(Buffer.from(code.slice(2), "hex"))
    .digest("hex");
};
if (
  proxy.is_fully_verified !== true ||
  implementation.is_fully_verified !== true ||
  hash(proxy.deployed_bytecode) !== profile.addressCodeSha256 ||
  hash(implementation.deployed_bytecode) !== profile.implementationCodeSha256 ||
  hash(probe.code) !== profile.addressCodeSha256 ||
  hash(probe.implementationCode) !== profile.implementationCodeSha256 ||
  probe.implementationSlot !== profile.implementationSlot ||
  probe.storage !==
    `0x${"0".repeat(24)}${text(profile.implementationAddress, "implementation").slice(2)}`
)
  throw new Error("token runtime evidence mismatch");
const accounting = await resource("protocols/pools", "basic-pool-accounting"),
  constants = object(accounting.constants, "accounting constants");
if (
  accounting.supportStatus !== "proposed" ||
  accounting.reviewStatus !== "pending-qualified-review" ||
  constants.feeIndexScale !== "1000000000000000000" ||
  constants.swapFeeDenominator !== "10000"
)
  throw new Error("invalid basic accounting generation");
const model = {
  feeIndexScale: constants.feeIndexScale,
  swapFeeDenominator: constants.swapFeeDenominator,
  musdc: {
    address: profile.tokenAddress,
    implementationAddress: profile.implementationAddress,
    implementationSlot: profile.implementationSlot,
    addressCodeSha256: profile.addressCodeSha256,
    implementationCodeSha256: profile.implementationCodeSha256,
  },
};
const output = await format(
  `// Generated by scripts/generate-pools-package.ts. Do not edit.\n// sha256:${digest.digest("hex")}\nexport const POOL_MODEL = ${JSON.stringify(model)} as const;\n`,
  {
    parser: "typescript",
    ...object(JSON.parse(await readFile(resolve(root, ".prettierrc.json"), "utf8")), "prettier"),
  },
);
const target = resolve(root, "packages/protocols/pools/src/model.generated.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(target, "utf8")) !== output) throw new Error("pool model drift");
} else await writeFile(target, output);
