import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadKnowledgeAuthoringExample } from "./lib/knowledge-authoring-example.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const defaultModuleRoot = resolve(
  repositoryRoot,
  "docs/guides/examples/knowledge-authoring/synthetic-widget-catalog",
);

interface Options {
  readonly check: boolean;
  readonly moduleRoot: string;
}

function parseArguments(arguments_: string[]): Options {
  let check = false;
  let moduleRoot = defaultModuleRoot;
  for (let index = 0; index < arguments_.length; index += 1) {
    const argument = arguments_[index];
    if (argument === "--check") {
      check = true;
      continue;
    }
    if (argument === "--module-root") {
      const path = arguments_[index + 1];
      if (!path || path.startsWith("--")) throw new Error("--module-root requires a path");
      moduleRoot = resolve(path);
      index += 1;
      continue;
    }
    throw new Error(`unknown argument '${String(argument)}'`);
  }
  return { check, moduleRoot };
}

const options = parseArguments(process.argv.slice(2));
const example = await loadKnowledgeAuthoringExample(options.moduleRoot);
const output = `<!-- Generated by scripts/generate-knowledge-authoring-example.ts. Do not edit. -->

# Synthetic widget reference

This is a documentation-only projection. It is not canonical Mezo knowledge,
does not appear in \`knowledge/index.json\`, and establishes no product or
protocol support.

- Input digest: \`sha256:${example.inputDigest}\`
- Module: \`${example.moduleId}\`
- Record: \`${example.recordId}\`
- Display name: ${example.displayName}
- Color: \`${example.color}\`
- Source: \`${example.sourceId}\` at revision \`${example.sourceRevision}\`
- Evidence: \`${example.evidenceId}\`
- Support: \`none\`
- Review: \`pending-qualified-review\`
`;

if (options.check) {
  let current: string;
  try {
    current = await readFile(example.generatedPath, "utf8");
  } catch (error) {
    throw new Error("synthetic generated reference is missing", { cause: error });
  }
  if (current !== output) {
    throw new Error("synthetic generated reference drifted; regenerate it");
  }
  process.stdout.write(
    `Synthetic knowledge-authoring reference is current (${example.inputDigest}).\n`,
  );
} else {
  await mkdir(dirname(example.generatedPath), { recursive: true });
  await writeFile(example.generatedPath, output, "utf8");
  process.stdout.write(
    `Generated synthetic knowledge-authoring reference (${example.inputDigest}).\n`,
  );
}
