import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  display,
  object,
  objects,
  parseJson,
  requiredRecord,
  scalar,
  text,
  values,
  type JsonObject,
} from "./lib/json.ts";
import { loadKnowledgeModule, resolveKnowledgeResource } from "./lib/knowledge-reference.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknown = process.argv.slice(2).filter((value) => value !== "--check");
if (unknown.length > 0) throw new Error(`unknown argument '${unknown[0]}'`);

function cell(value: unknown): string {
  return display(value, "table cell").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers: unknown[], rows: unknown[][]): string {
  return [
    `| ${headers.map(cell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

const module = await loadKnowledgeModule(repositoryRoot, "workflows/transactions");
const generated = module.index.resources.find(
  (resource) => resource.id === "transaction-reference",
);
if (generated?.role !== "generated")
  throw new Error("transaction-reference generated resource is missing");
const outputPath = resolve(module.directory, generated.path);
const relation = relative(module.directory, outputPath);
if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`)) {
  throw new Error("transaction reference output escapes its module");
}

const digest = createHash("sha256");
digest.update(await readFile(module.indexPath));
const byId = new Map<string, JsonObject>();
for (const reference of objects(generated.generatedFrom, "transaction reference inputs")) {
  const moduleId = text(reference.moduleId, "transaction reference module ID");
  const resourceId = text(reference.resourceId, "transaction reference resource ID");
  const resolved = await resolveKnowledgeResource(repositoryRoot, reference);
  const bytes = await readFile(resolved.path);
  digest.update(`${moduleId}:${resourceId}\0`);
  digest.update(bytes);
  digest.update("\0");
  byId.set(resourceId, object(parseJson(bytes.toString("utf8"), resourceId), resourceId));
}

const machine = required("transaction-state-machine");
const requirements = required("transaction-client-requirements");
const errors = required("transaction-errors");
const matrix = required("transaction-requirement-matrix");
const observations = required("transaction-mezo-observations");
const inputDigest = digest.digest("hex");
const coreStates = ["submitted", "included", "confirmed", "reconciled"].map((id) => {
  const state = requiredRecord(objects(machine.states, "transaction states"), "id", id, "state");
  return [
    text(state.id, `${id} state ID`),
    scalar(state.terminal, `${id} terminal flag`),
    scalar(state.successLevel, `${id} success level`),
  ];
});
const extensions = object(module.index.extensions, "transaction module extensions");

const output = [
  "<!-- Generated by scripts/generate-transaction-reference.ts. Do not edit. -->",
  "",
  "# Transaction and RPC knowledge reference",
  "",
  "This is a deterministic projection of indexed knowledge, not an independent authority or an accepted public API.",
  "",
  "- Module: `workflows/transactions`",
  `- Knowledge status: \`${display(module.index.status, "module status")}\``,
  `- Support: \`${display(module.index.supportStatus, "module support")}\``,
  `- Review: \`${display(module.index.reviewStatus, "module review")}\``,
  `- Architecture: \`${display(extensions.architectureStatus, "architecture status")}\``,
  `- Input digest: \`sha256:${inputDigest}\``,
  "",
  "## Fact and proposal boundary",
  "",
  text(extensions.factProposalBoundary, "fact/proposal boundary"),
  "",
  table(
    ["Resource", "Evidence status", "Support", "Review"],
    [
      [
        "State machine",
        scalar(machine.status, "state-machine status"),
        scalar(machine.supportStatus, "state-machine support"),
        scalar(machine.reviewStatus, "state-machine review"),
      ],
      [
        "Client requirements",
        scalar(requirements.status, "requirements status"),
        scalar(requirements.supportStatus, "requirements support"),
        scalar(requirements.reviewStatus, "requirements review"),
      ],
      [
        "Error taxonomy",
        scalar(errors.status, "errors status"),
        scalar(errors.supportStatus, "errors support"),
        scalar(errors.reviewStatus, "errors review"),
      ],
      [
        "Requirement matrix",
        scalar(matrix.status, "matrix status"),
        scalar(matrix.supportStatus, "matrix support"),
        scalar(matrix.reviewStatus, "matrix review"),
      ],
      [
        "Mezo observations",
        scalar(observations.status, "observations status"),
        scalar(observations.supportStatus, "observations support"),
        scalar(observations.reviewStatus, "observations review"),
      ],
    ],
  ),
  "",
  "## Inventory",
  "",
  table(
    ["Content", "Count"],
    [
      ["Lifecycle states", values(machine.states, "states").length],
      ["Lifecycle transitions", values(machine.transitions, "transitions").length],
      ["Client requirements", values(requirements.requirements, "requirements").length],
      ["Error categories", values(errors.errors, "errors").length],
      ["Mezo observations", values(observations.observations, "observations").length],
      ["Protocol domains", values(matrix.domains, "domains").length],
    ],
  ),
  "",
  "## Lifecycle distinction",
  "",
  table(["State", "Terminal", "Success level"], coreStates),
  "",
  "Only `reconciled` is protocol success. Timeout, replacement, cancellation, reorg, approval, and reconciliation failure retain the machine-readable behavior in `transaction-state-machine`.",
  "",
  "## Evidence-backed Mezo observations",
  "",
  table(
    ["Observation", "Classification", "Consequence"],
    objects(observations.observations, "observations").map((observation) => [
      scalar(observation.id, "observation ID"),
      scalar(observation.classification, "observation classification"),
      scalar(observation.workflowConsequence, "observation consequence"),
    ]),
  ),
  "",
  "## Protocol routing",
  "",
  table(
    ["Task", "Domain", "Knowledge resource", "Domain support state"],
    objects(matrix.domains, "matrix domains").map((domain) => {
      const reference = object(domain.knowledgeReference, "domain knowledge reference");
      return [
        scalar(domain.taskId, "domain task ID"),
        scalar(domain.domain, "domain name"),
        `${text(reference.moduleId, "domain module ID")}:${text(reference.resourceId, "domain resource ID")}`,
        scalar(domain.supportStatus, "domain support status"),
      ];
    }),
  ),
  "",
  "## Production boundary",
  "",
  "The v0.4 module structure, logical references, schemas, generator, and validators are production-ready. ADR-0002 and ADR-0003 are accepted. No public client interface, dependency choice, package implementation, or supported writer is implied.",
  "",
].join("\n");

if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("generated/reference.md is missing; run the generator without --check");
  }
  if (current !== output) throw new Error("workflows/transactions generated reference drifted");
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

process.stdout.write(`workflows/transactions reference is current (${inputDigest}).\n`);

function required(resourceId: string): JsonObject {
  const value = byId.get(resourceId);
  if (value === undefined) throw new Error(`required resource '${resourceId}' is missing`);
  return value;
}
