import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";
import { object } from "./lib/json.ts";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
if (process.argv.slice(2).some((arg) => arg !== "--check"))
  throw new Error("usage: generate-redemption-package.ts [--check]");
const source = await loadKnowledgeReference(root, {
  moduleId: "protocols/musd/redemptions",
  resourceId: "redemption-formulas",
});
const record = object(source.document, "redemption formulas");
if (record.status !== "verified" || record.reviewStatus !== "accepted")
  throw new Error("redemption formula lifecycle differs");
const model = object(record.constants, "redemption constants"),
  digest = createHash("sha256")
    .update(await readFile(source.path))
    .digest("hex");
const output = await format(
  `// Generated by scripts/generate-redemption-package.ts. Do not edit.\n// sha256:${digest}\nexport const REDEMPTION_MODEL = ${JSON.stringify(model)} as const;\n`,
  {
    parser: "typescript",
    ...object(JSON.parse(await readFile(resolve(root, ".prettierrc.json"), "utf8")), "prettier"),
  },
);
const path = resolve(root, "packages/protocols/musd-redemptions/src/model.generated.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(path, "utf8")) !== output) throw new Error("redemption model drift");
} else await writeFile(path, output);
