import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  display,
  object,
  objects,
  parseJson,
  scalar,
  text,
  texts,
  values,
  type JsonObject,
} from "./lib/json.ts";
import { loadKnowledgeModule, resolveKnowledgeResource } from "./lib/knowledge-reference.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknown = process.argv.slice(2).filter((value) => value !== "--check");
if (unknown.length > 0) throw new Error(`unknown argument '${unknown[0]}'`);

function cell(value: unknown): string {
  return display(value, "table cell").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers: unknown[], rows: unknown[][]): string {
  return [
    `| ${headers.map(cell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

const module = await loadKnowledgeModule(repositoryRoot, "protocols/incentives");
const generated = module.index.resources.find((resource) => resource.id === "incentives-reference");
if (generated?.role !== "generated")
  throw new Error("incentives-reference generated resource is missing");
const outputPath = resolve(module.directory, generated.path);
const relation = relative(module.directory, outputPath);
if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`))
  throw new Error("incentives reference output escapes its module");

const digest = createHash("sha256");
digest.update(await readFile(module.indexPath));
const byId = new Map<string, JsonObject>();
for (const reference of objects(generated.generatedFrom, "incentives reference inputs")) {
  const moduleId = text(reference.moduleId, "incentives reference module ID");
  const resourceId = text(reference.resourceId, "incentives reference resource ID");
  const resolved = await resolveKnowledgeResource(repositoryRoot, reference);
  const bytes = await readFile(resolved.path);
  digest.update(`${moduleId}:${resourceId}\0`);
  digest.update(bytes);
  digest.update("\0");
  byId.set(resourceId, object(parseJson(bytes.toString("utf8"), resourceId), resourceId));
}

const locks = required("incentives-locks");
const contractRoles = required("incentives-contract-roles");
const boost = required("incentives-boost");
const gauges = required("incentives-gauges-rewards");
const emissions = required("incentives-emissions");
const validatorModel = required("incentives-validator-voting-rewards");
const operations = required("incentives-operations");
const fixtures = required("incentives-formula-fixtures");
const validatorFixtures = required("incentives-validator-allocation-fixtures");
const topology = required("incentives-mainnet-topology");
const emissionEvidence = required("incentives-emissions-mainnet");
const validatorEvidence = required("incentives-validator-allocation-mainnet");
const reproduction = required("incentives-source-reproduction");
const writer = required("incentives-writer-integration");
const inputDigest = digest.digest("hex");
const scope = object(module.index.scope, "incentives module scope");
const extensions = object(module.index.extensions, "incentives module extensions");
const currentValidatorState = object(
  validatorEvidence.currentBoundaryState,
  "validator current boundary state",
);
const validatorSnapshot = object(validatorEvidence.networkSnapshot, "validator network snapshot");
const validatorHistory = object(validatorEvidence.lifecycleHistory, "validator lifecycle history");
const rewardNotification = object(
  validatorEvidence.representativeRewardNotification,
  "representative reward notification",
);

const output = [
  "<!-- Generated by scripts/generate-incentives-reference.ts. Do not edit. -->",
  "",
  "# Mezo incentives evidence reference",
  "",
  "This is a deterministic projection of indexed canonical knowledge, not an independent authority.",
  "",
  "- Module: `protocols/incentives`",
  `- Support: \`${display(module.index.supportStatus, "module support")}\``,
  `- Review: \`${display(module.index.reviewStatus, "module review")}\``,
  `- Verified: \`${display(module.index.verifiedAt, "module verification date")}\``,
  `- Review after: \`${display(module.index.reviewAfter, "module review date")}\``,
  `- Evidence block: \`${display(scope.blockNumber, "evidence block")}\` on \`mezo-mainnet\``,
  `- Input digest: \`sha256:${inputDigest}\``,
  "",
  "## Inventory",
  "",
  table(
    ["Resource", "Count"],
    [
      ["Lock assets", values(locks.assets, "lock assets").length],
      ["Lock formulas", values(locks.formulas, "lock formulas").length],
      ["Gauge types", values(gauges.gaugeTypes, "gauge types").length],
      ["Emission formulas", values(emissions.formulas, "emission formulas").length],
      ["Validator formulas", values(validatorModel.formulas, "validator formulas").length],
      ["Operations", values(operations.records, "operations").length],
      [
        "Formula fixtures",
        values(fixtures.records, "formula fixtures").length +
          values(validatorFixtures.records, "validator fixtures").length,
      ],
      ["Stable contract roles", values(contractRoles.records, "contract roles").length],
      ["Topology evidence roles", values(topology.contracts, "topology contracts").length],
      [
        "Emission topology evidence roles",
        values(emissionEvidence.contracts, "emission contracts").length,
      ],
      [
        "Dynamic validator gauges at validator evidence block",
        scalar(currentValidatorState.gaugeCount, "validator gauge count"),
      ],
      ["Source reproduction records", values(reproduction.records, "reproductions").length],
      ["Historical writer integrations", values(writer.operations, "writer operations").length],
    ],
  ),
  "",
  "## Lock assets",
  "",
  table(
    ["Role", "Maximum lock", "Boostable"],
    objects(locks.assets, "lock assets").map((asset) => [
      scalar(asset.id, "lock asset ID"),
      `${display(asset.maxLockWeeks, "maximum lock weeks")} weeks`,
      scalar(asset.boostable, "boostable flag"),
    ]),
  ),
  "",
  "## Formula boundary",
  "",
  table(
    ["Formula", "Expression / rule"],
    [
      ...formulaRows(locks.formulas, "lock formulas", "expression"),
      formulaRow(object(boost.formula, "boost formula"), "expression"),
      [
        "emission-global-index",
        scalar(
          object(gauges.emissionAllocation, "emission allocation").globalIndex,
          "global index",
        ),
      ],
      [
        "gauge-emission-share",
        scalar(
          object(gauges.emissionAllocation, "emission allocation").gaugeAccrual,
          "gauge accrual",
        ),
      ],
      ...formulaRows(emissions.formulas, "emission formulas", "integerOrder"),
      ...formulaRows(validatorModel.formulas, "validator formulas", "integerOrder"),
    ],
  ),
  "",
  "## Emission accounting boundary",
  "",
  "The active minter creates one epoch emission budget. Rebase and reward amounts partition that budget; they are transfers to separate destinations, not additive mints. Splitter needles are governed state and must be read for the relevant pre-state.",
  "",
  "The specification describes locked veMEZO supply, while the active minter uses prior-boundary unboosted, time-decayed voting power. The deployed input and exact integer order govern this version-scoped model; the disagreement remains recorded as a conflict.",
  "",
  "## Validator allocation boundary",
  "",
  `At block \`${display(validatorSnapshot.blockNumber, "validator block")}\`, ${display(currentValidatorState.gaugeCount, "validator gauge count")} dynamic validator gauges sum exactly to voter \`totalWeight\`. Current weights remain live persistent state; they are not settled reward amounts.`,
  "",
  `The bounded history contains ${display(validatorHistory.voterLogCount, "voter log count")} relevant voter events. The representative reward notification floors ${display(rewardNotification.floorDustRaw, "reward floor dust")} raw MEZO units across gauge-index shares; its actual event amount remains authoritative.`,
  "",
  "Validator voting is independent from pool voting. Raw locked BTC, unboosted veBTC power, boosted veBTC power, external relative vote inputs, resulting gauge weights, indexed claimable amounts, distributed MEZO, and claimed MEZO remain separate typed values.",
  "",
  "The current official Validator Gauge guide agrees with persistent per-validator voting, while another pinned official validator guide says rewards are equal and not vote-directed. The active executable plus event/state evidence governs the current generation; the disagreement remains explicit documentation drift.",
  "",
  "## Deployment and writer boundary",
  "",
  "Fifteen deployed roles resolve through accepted Contracts deployment and ABI records with activation histories. validator evidence review accepted the two reusable validator factory roots; their dynamic children remain evidence-scoped instances rather than static registry identities. Registry and protocol review acceptance create no incentives-operation, reader, or writer support.",
  "",
  "All twelve operation records describe verified state-machine behavior, but module support is `none`. Historical create-lock and replacement-vote replay proves only those calls at their exact historical pre-states.",
  "",
  "Remaining public-capability blockers:",
  "",
  ...texts(extensions.blockers, "incentives blockers").map((blocker) => `- ${blocker}`),
  "",
  "APR, APY, forecasts, and user yield are analytics and are not protocol outputs.",
  "",
].join("\n");

if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("generated/reference.md is missing; run the generator without --check");
  }
  if (current !== output) throw new Error("protocols/incentives generated reference drifted");
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

process.stdout.write(`protocols/incentives reference is current (${inputDigest}).\n`);

function required(resourceId: string): JsonObject {
  const value = byId.get(resourceId);
  if (value === undefined) throw new Error(`required resource '${resourceId}' is missing`);
  return value;
}

function formulaRows(value: unknown, label: string, expressionKey: string): unknown[][] {
  return objects(value, label).map((formula) => formulaRow(formula, expressionKey));
}

function formulaRow(formula: JsonObject, expressionKey: string): unknown[] {
  const expression = formula[expressionKey];
  return [
    scalar(formula.id, "formula ID"),
    Array.isArray(expression)
      ? texts(expression, "formula expression").join("; ")
      : scalar(expression, "formula expression"),
  ];
}
