import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";
import { object, objects, text } from "./lib/json.ts";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
if (process.argv.slice(2).some((arg) => arg !== "--check"))
  throw new Error("usage: generate-institutional-package.ts [--check]");
const digest = createHash("sha256");
async function resource(id: string) {
  const loaded = await loadKnowledgeReference(root, {
    moduleId: "protocols/musd/institutional-debt",
    resourceId: id,
  });
  digest.update(await readFile(loaded.path));
  const record = object(loaded.document, id);
  if (record.status !== "verified" || record.reviewStatus !== "accepted")
    throw new Error("institutional input is not accepted");
  return record;
}
const formulas = await resource("institutional-debt-formulas"),
  vaults = await resource("institutional-debt-enclave-vaults"),
  accounting = await resource("institutional-debt-positions-accounting");
const model = {
  constants: object(formulas.constants, "constants"),
  statuses: object(accounting.positionModel, "position model").status,
  enclaves: objects(vaults.generations, "generations").map((entry) => ({
    generation: text(entry.id, "generation"),
    contractId: text(entry.contractId, "contract ID"),
    roles: Object.keys(object(entry.roleBoundary, "roles")),
    genericTargetExclusions: entry.genericTargetExclusions ?? [],
  })),
};
const output = await format(
  `// Generated by scripts/generate-institutional-package.ts. Do not edit.\n// sha256:${digest.digest("hex")}\nexport const INSTITUTIONAL_MODEL = ${JSON.stringify(model)} as const;\n`,
  {
    parser: "typescript",
    ...object(JSON.parse(await readFile(resolve(root, ".prettierrc.json"), "utf8")), "prettier"),
  },
);
const path = resolve(root, "packages/protocols/musd-institutional-debt/src/model.generated.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(path, "utf8")) !== output) throw new Error("institutional model drift");
} else await writeFile(path, output);
