import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  display,
  object,
  objects,
  parseJson,
  scalar,
  text,
  texts,
  type JsonObject,
} from "./lib/json.ts";
import { loadKnowledgeModule, resolveKnowledgeResource } from "./lib/knowledge-reference.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const unknown = process.argv.slice(2).filter((value) => value !== "--check");
if (unknown.length > 0) throw new Error(`unknown argument '${unknown[0]}'`);

function cell(value: unknown): string {
  return display(value, "table cell").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers: unknown[], rows: unknown[][]): string {
  return [
    `| ${headers.map(cell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

function logicalReference(reference: JsonObject): string {
  let value = `${text(reference.moduleId, "reference module ID")}:${text(reference.resourceId, "reference resource ID")}`;
  if (reference.recordId) value += `#${text(reference.recordId, "reference record ID")}`;
  if (reference.pointer) value += text(reference.pointer, "reference pointer");
  return value;
}

const module = await loadKnowledgeModule(repositoryRoot, "troubleshooting");
const generated = module.index.resources.find(
  (resource) => resource.id === "troubleshooting-reference",
);
if (generated?.role !== "generated")
  throw new Error("troubleshooting-reference generated resource is missing");
const outputPath = resolve(module.directory, generated.path);
const relation = relative(module.directory, outputPath);
if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`)) {
  throw new Error("troubleshooting reference output escapes its module");
}

const digest = createHash("sha256");
digest.update(await readFile(module.indexPath));
const issues: { resourceId: string; issue: JsonObject }[] = [];
for (const reference of objects(generated.generatedFrom, "troubleshooting reference inputs")) {
  const moduleId = text(reference.moduleId, "troubleshooting reference module ID");
  const resourceId = text(reference.resourceId, "troubleshooting reference resource ID");
  const resolved = await resolveKnowledgeResource(repositoryRoot, reference);
  const bytes = await readFile(resolved.path);
  digest.update(`${moduleId}:${resourceId}\0`);
  digest.update(bytes);
  digest.update("\0");
  issues.push({
    resourceId,
    issue: object(parseJson(bytes.toString("utf8"), resourceId), resourceId),
  });
}
const inputDigest = digest.digest("hex");

const sections = issues.flatMap(({ resourceId, issue }) => [
  `## ${display(issue.id, "issue ID")}`,
  "",
  `- Resource: \`troubleshooting:${resourceId}\``,
  `- Category / severity: \`${display(issue.category, "issue category")}\` / \`${display(issue.severity, "issue severity")}\``,
  `- Evidence status: \`${display(issue.issueStatus, "issue status")}\``,
  `- Review: \`${display(issue.reviewStatus, "issue review")}\``,
  `- Verified: \`${display(issue.verifiedAt, "issue verification date")}\``,
  `- Review after: \`${display(issue.reviewAfter, "issue review date")}\``,
  `- Reproduction basis: \`${display(object(issue.reproduction, "issue reproduction").basis, "reproduction basis")}\``,
  "",
  "### Symptom",
  "",
  text(issue.symptom, "issue symptom"),
  "",
  "### Scope",
  "",
  "```json",
  JSON.stringify(issue.scope, null, 2),
  "```",
  "",
  "### Prerequisites",
  "",
  ...texts(issue.prerequisites, "issue prerequisites").map((item) => `- ${item}`),
  "",
  "### Diagnostic steps",
  "",
  ...texts(issue.diagnosticSteps, "issue diagnostic steps").map(
    (item, index) => `${index + 1}. ${item}`,
  ),
  "",
  "### Interpretation",
  "",
  `- Expected: ${display(issue.expected, "expected behavior")}`,
  `- Observed: ${display(issue.observed, "observed behavior")}`,
  `- Control: ${display(issue.control, "control behavior")}`,
  `- Verified cause: ${display(issue.verifiedCause, "verified cause")}`,
  "",
  "### Safe mitigation",
  "",
  text(issue.safeMitigation, "safe mitigation"),
  "",
  "### Canonical owners",
  "",
  ...objects(issue.canonicalLinks, "canonical links").map(
    (reference) => `- \`${logicalReference(reference)}\``,
  ),
  "",
  "### Limitations",
  "",
  ...texts(issue.limitations, "issue limitations").map((item) => `- ${item}`),
  "",
]);

const output = [
  "<!-- Generated by scripts/generate-troubleshooting-reference.ts. Do not edit. -->",
  "",
  "# Troubleshooting reference",
  "",
  "This is a deterministic human projection of indexed issue records. Underlying network, contract, protocol, and workflow facts remain owned by the cited modules.",
  "",
  "- Module: `troubleshooting`",
  `- Knowledge status: \`${display(module.index.status, "module status")}\``,
  `- Support: \`${display(module.index.supportStatus, "module support")}\``,
  `- Review: \`${display(module.index.reviewStatus, "module review")}\``,
  `- Review after: \`${display(module.index.reviewAfter, "module review date")}\``,
  `- Input digest: \`sha256:${inputDigest}\``,
  "",
  "## Issue inventory",
  "",
  table(
    ["Issue", "Category", "Severity", "Evidence scope", "Review after"],
    issues.map(({ issue }) => [
      scalar(issue.id, "issue ID"),
      scalar(issue.category, "issue category"),
      scalar(issue.severity, "issue severity"),
      scalar(issue.issueStatus, "issue status"),
      scalar(issue.reviewAfter, "issue review date"),
    ]),
  ),
  "",
  "## Safety boundary",
  "",
  "Apply only the issue's bounded mitigation. Never treat an absent RPC result as failure, copied documentation as deployed truth, a source-chain receipt as cross-chain completion, or a workaround as authority to bypass validation or replay value. Security findings follow `SECURITY.md` and are not published here.",
  "",
  ...sections,
].join("\n");

if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("generated/reference.md is missing; run the generator without --check");
  }
  if (current !== output) throw new Error("troubleshooting generated reference drifted");
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

process.stdout.write(`Troubleshooting reference is current (${inputDigest}).\n`);
