import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { generateHistoricalContractEvidence } from "../packages/contracts/tools/historical-evidence.ts";
import { generateNttContractInterfaces } from "./lib/ntt-contract-generation.ts";

import {
  assertGeneratedPackageCurrent,
  buildContractsPackageFile,
} from "./lib/foundational-package-generation.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(repositoryRoot, "packages/contracts/src/data.generated.ts");
assertInsidePackage(outputPath, "contracts");
const checkOnly = parseArguments(process.argv.slice(2));
const generated = await buildContractsPackageFile(repositoryRoot);
const historical = await generateHistoricalContractEvidence(repositoryRoot);
const ntt = await generateNttContractInterfaces(repositoryRoot);
const nttPath = resolve(repositoryRoot, "packages/contracts/src/ntt.generated.ts");
const nttOutput = await format(
  `// Generated by scripts/generate-contracts-package.ts. Do not edit.\n// sha256:${ntt.digest}\nexport const NTT_CONTRACT_INTERFACES = ${JSON.stringify(ntt.records)} as const;\n`,
  { ...(await resolveConfig(nttPath)), parser: "typescript" },
);
const historicalPath = resolve(repositoryRoot, "packages/contracts/src/historical.generated.ts");
const historicalOutput = await format(
  `// Generated by scripts/generate-contracts-package.ts. Do not edit.\n// Canonical evidence digest: ${historical.digest}\nimport type { GeneratedHistoricalEvidence } from "./historical.ts";\nexport const HISTORICAL_CONTRACT_EVIDENCE = ${JSON.stringify(historical.records)} as const satisfies readonly GeneratedHistoricalEvidence[];\n`,
  { ...(await resolveConfig(historicalPath)), parser: "typescript" },
);

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch((error: unknown) => {
    throw new Error("Contracts generated data is missing; run the generator", { cause: error });
  });
  assertGeneratedPackageCurrent(current, generated, "Contracts");
  if ((await readFile(historicalPath, "utf8")) !== historicalOutput)
    throw new Error("Historical Contracts projection is stale; run the generator");
  if ((await readFile(nttPath, "utf8")) !== nttOutput)
    throw new Error("NTT Contracts projection is stale; run the generator");
} else {
  await writeFile(outputPath, generated.output, "utf8");
  await writeFile(historicalPath, historicalOutput, "utf8");
  await writeFile(nttPath, nttOutput, "utf8");
}
process.stdout.write(`Contracts package data is current (${generated.digest}).\n`);

function parseArguments(arguments_: readonly string[]): boolean {
  const unknown = arguments_.filter((argument) => argument !== "--check");
  if (unknown.length > 0) throw new Error(`unknown argument '${unknown[0]}'`);
  return arguments_.includes("--check");
}

function assertInsidePackage(path: string, packageName: string): void {
  const packageRoot = resolve(repositoryRoot, "packages", packageName);
  const relation = relative(packageRoot, path);
  if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`)) {
    throw new Error(`${packageName} generated output escapes its package`);
  }
}
