import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { loadKnowledgeReference } from "./lib/knowledge-reference.ts";
import { object, objects, text as string } from "./lib/json.ts";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
if (process.argv.slice(2).some((arg) => arg !== "--check"))
  throw new Error("usage: generate-prices-package.ts [--check]");
const hash = createHash("sha256");
async function record(resourceId: string) {
  const source = await loadKnowledgeReference(root, { moduleId: "prices", resourceId });
  const bytes = await readFile(source.path);
  hash.update(bytes);
  return object(source.document, resourceId);
}
const taxonomy = await record("price-source-taxonomy"),
  rules = await record("price-datum-rules"),
  freshness = await record("price-freshness-fallback-rules"),
  feeds = await record("price-sources-feeds");
const classes = objects(taxonomy.records, "classes").map((entry) => string(entry.id, "class"));
if (
  classes.length !== 6 ||
  new Set(classes).size !== 6 ||
  object(rules.scope, "scope").maxPowerOfTenExponent !== 77 ||
  object(freshness.freshness, "freshness").valid !==
    "publishTime <= asOf and asOf - publishTime <= maxAgeSeconds"
)
  throw new Error("unsupported price rules");
const feed = objects(feeds.feeds, "feeds").find((entry) => entry.id === "feed.skip-btc-usd");
const source = objects(feeds.sources, "sources").find((entry) => entry.id === feed?.sourceId);
if (
  !feed ||
  source?.sourceClass !== "pushed-feed-observation" ||
  source.confidenceSemantics !== null
)
  throw new Error("unsupported Skip source");
const reference = object(
  object(source.networkScopedContractReferences, "networks")["mezo-mainnet"],
  "mainnet",
);
const model = {
  sourceClasses: classes,
  maxPowerOfTenExponent: 77,
  rounding: object(rules.scaling, "scaling").roundingRules,
  skip: {
    sourceId: source.id,
    feedId: feed.id,
    baseAsset: feed.baseAsset,
    quoteAsset: feed.quoteAsset,
    sourceDecimals: feed.sourceDecimals,
    contractId: string(reference.recordId, "record ID").split("@")[0],
  },
};
const output = await format(
  `// Generated by scripts/generate-prices-package.ts. Do not edit.\n// sha256:${hash.digest("hex")}\nexport const PRICE_MODEL = ${JSON.stringify(model)} as const;\n`,
  {
    parser: "typescript",
    ...object(JSON.parse(await readFile(resolve(root, ".prettierrc.json"), "utf8")), "prettier"),
  },
);
const path = resolve(root, "packages/prices/src/model.generated.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(path, "utf8")) !== output) throw new Error("price model drift");
} else await writeFile(path, output);
