// Generated by scripts/generate-savings-package.ts. Do not edit.
// Canonical resources: Savings model/roles/reconciliation; Contracts dynamic interface profiles.
export const SAVINGS_INPUT_DIGEST = "59b9613c6bf5ef77a32d34a342f2b0dbe334e1bcc14100749b686ab0b996885f";
export const SAVINGS_SCALE = 1000000000000000000n;
export const SAVINGS_RUNTIME_SHA256 = "8739fb3a70a6679d5b5355085505328922150dd91f2db20ee19a2e4cd6bf4565";
export const SAVINGS_NETWORK = "mezo-mainnet";
export const IMPLEMENTATION_SLOT = "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc" as const;
export const SAVINGS_ROOTS = {
  "savings-deployment": "musd.savings-rate",
  "musd-token": "musd.token",
  "pcv": "musd.pcv",
  "pools-voter": "incentives.pools-voter"
} as const;
export const SAVINGS_EVIDENCE = {
  "verifiedAt": "2026-08-23T20:17:37Z",
  "reviewAfter": "2026-09-23T00:00:00Z",
  "supportStatus": "proposed",
  "reviewStatus": "accepted"
} as const;
export const SAVINGS_ROLE_TEMPLATES = {
  "strategy": {
    "runtimeSha256": "4c88bbe8b121f96e87c29460ff853535f8097a981072d1eaca11a1a72f83d01d",
    "proxy": false,
    "readAbi": [
      {
        "inputs": [],
        "name": "token",
        "outputs": [
          {
            "internalType": "contract IERC20",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "vault",
        "outputs": [
          {
            "internalType": "address",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      }
    ]
  },
  "converter": {
    "runtimeSha256": "1d190ab63fdba4256fb9d4c43daba20c85603822a6880cb32d08be7ce1970633",
    "proxy": true,
    "readAbi": [
      {
        "inputs": [],
        "name": "musdSavingsRate",
        "outputs": [
          {
            "internalType": "contract IMUSDSavingsRate",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "musdToken",
        "outputs": [
          {
            "internalType": "contract IERC20",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "maxSlippageBps",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      }
    ]
  },
  "gauge": {
    "runtimeSha256": "8ce22fe1bb4aeca962abd1c1c01e1b4dd9e85629f03e82011c4ea1fa6cfeb654",
    "proxy": false,
    "readAbi": [
      {
        "inputs": [],
        "name": "stakingToken",
        "outputs": [
          {
            "internalType": "address",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "voter",
        "outputs": [
          {
            "internalType": "address",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "rewardToken",
        "outputs": [
          {
            "internalType": "address",
            "name": "",
            "type": "address"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "address",
            "name": "",
            "type": "address"
          }
        ],
        "name": "balanceOf",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "totalSupply",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "address",
            "name": "_account",
            "type": "address"
          }
        ],
        "name": "earned",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "fees",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      }
    ]
  }
} as const;
