// Generated by scripts/generate-institutional-package.ts. Do not edit.
// sha256:747543c0231c9a986ff91c8328d6cf124a35975eb52f2492abbc58d13389aece
export const INSTITUTIONAL_MODEL = {
  constants: {
    basisPoints: "10000",
    secondsInYear: "31556952",
    ratioPrecision: "1000000000000000000",
    maxUint256: "115792089237316195423570985008687907853269984665640564039457584007913129639935",
  },
  statuses: ["nonExistent", "active", "closedByRepayment", "closedByLiquidation"],
  enclaves: [
    {
      generation: "original",
      contractId: "musd.enclave-v1",
      roles: ["DEFAULT_ADMIN_ROLE", "EXECUTOR_ROLE", "BTC_MANAGER_ROLE", "BRIDGE_MODULE_ROLE"],
      genericTargetExclusions: [],
    },
    {
      generation: "second",
      contractId: "musd.enclave-v2",
      roles: [
        "DEFAULT_ADMIN_ROLE",
        "EXECUTOR_ROLE",
        "BTC_MANAGER_ROLE",
        "BRIDGE_MANAGER_ROLE",
        "BRIDGE_MODULE_ROLE",
      ],
      genericTargetExclusions: ["AssetsBridge", "veBTC"],
    },
  ],
} as const;
