// Generated by scripts/generate-pools-package.ts. Do not edit.
// sha256:69c8b604eb7e472e427fd232b4fc96b21e9d9c1808a71791b6d52dacfc776ac8
export const POOL_MODEL = {
  feeIndexScale: "1000000000000000000",
  swapFeeDenominator: "10000",
  musdc: {
    address: "0x04671c72aab5ac02a03c1098314b1bb6b560c197",
    implementationAddress: "0x09d42a1c4792546c26451af2d373bf0d4c545baf",
    implementationSlot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc",
    addressCodeSha256: "4bc884c60f64f3486dd8c1a31ede2542f7417edc9e94730d9a86ae386cb82f65",
    implementationCodeSha256: "378d40bcb07169de058746028e58f77128dcde6ff1660a70dbe338a7e700abc2",
  },
} as const;
